### ISSUE TITLE
Página de cada video- Ajuste de botón descargar y compartir

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Paty#10]
@FAAREIA y @mkreyness : ayer @FAAREIA me dijo que hizo unos cambios en los botones para que queden el compartir y el descargar más armónicos y no lo veo aplicado en la página. Subamoslo lo antes posible porfa.

**Comment by FAAREIA** [comment]
El original a seguir es este:
http://www.benteveo.tv/_paty-chile-sitio/video.html

El código del botón es el que pasé a ayer, acordate que lo genera facebook, no es custom.

**Comment by LeandroBraier** [comment]
Perfecto @FAAREIA Confirmanos @mkreyness si está todo OK porfa.

**Comment by mkreyness** [comment]
Pero quedamos en que eso no se podia hacer, usa el sharer que no funciona.
A mi facebook me genera lo que ven, otra cosa no puedo hacer.
Si no pongo la clase que estoy poniendo, chau compartir.

**Comment by mkreyness** [comment]
Aparte se ve pisoteado por el otro boton, esto es tomando del URL de benteveo.
![pisoteo](https://cloud.githubusercontent.com/assets/6135791/16881345/23fd2bc8-4a90-11e6-8358-26a33211593f.JPG)

Y si, no tengo el browser maximizado, pero no podemos depender de que la gente tenga su browser maximizado.

**Comment by LeandroBraier** [comment]
@FAAREIA porfa resolvelo. Usá el sharer que pide MK, tal como hablamos ayer. Porfa.

**Comment by mkreyness** [comment]
no es algo visible que él pueda usar. Es lo que ocurre cuando se usa la clase "fb-like", que obligatoriamente pone los DOS botones (el de share es opcional, el de like no) y que NO tiene otro tamaño mas grande que el que pongo. Es codigo metido automaticamente por un widget de Facebook que BUSCA la clase "fb-like" y la reemplaza por esto. No hay forma de que Fede lo "intervenga" para que se vea diferente.

**Comment by mkreyness** [comment]
Si pongo otra clase que no sea "fb-like", simplemente desaparece todo.

**Comment by LeandroBraier** [comment]
Ok, @FAAREIA hagamos lo que dice MK porfa y dejemoslo cerrado, que hoy la gente va a empezar a entrar.

**Comment by FAAREIA** [comment]
`<div class="fb-share-button contenido" data-href="http://benteveo.tv/" data-layout="button" data-size="large" data-mobile-iframe="true"></div>`

**Comment by mkreyness** [comment]
Ahi con eso se ve mejor y sigue andando. No podriamos compartir un URL que no fuera el propio, pero como igual lo que queremos es eso, estamos bien.

**Comment by LeandroBraier** [comment]
Genial! Gracias a los dos!
