### ISSUE TITLE
Sistema Paty Chile- La Diaria

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Paty#11]
@mkreyness yo no veo subido nada en el CMS. Todavía no subieron nada no?

**Comment by mkreyness** [comment]
Hasta ahora no aparecieron archivos ni me avisaron de ningun problema, asi que supongo que estaran juntando todo para hacerlo el lunes.

**Comment by LeandroBraier** [comment]
@mkreyness el CMS no me muestra los listados. Te fijás qué puede ser?

**Comment by mkreyness** [comment]
No va a mostrarte nada hasta que terminen de subir datos. No se procesa hasta que este completa (que llegue el archivo participantes.txt, que no esta).
De cuando termine de llegar, pasara un rato hasta que terminen de estar todos, pero vas a irlos viendo a medida que se procesan.

**Comment by LeandroBraier** [comment]
Entendiste mal. No me refiero a que me muestra los listados vacios. Quiero decir que no los muestra directamente. Mirá la captura:

<img width="1568" alt="captura de pantalla 2016-07-25 a las 5 03 06 p m" src="https://cloud.githubusercontent.com/assets/6719872/17114653/3fb169e4-5286-11e6-904d-0120ad6f3c40.png">

Recordá que estoy accediendo con Usuario Root. Si tenés el admin te agradezco.

**Comment by mkreyness** [comment]
espera que por lo que veo se corrompio algo entonces.

**Comment by mkreyness** [comment]
el problema es que SE LLENO EL DISCO !
Los videos estan pesando mucho mas de lo que estaba previsto.
No van a poder seguir subiendo nada, frenalos por favor hasta que yo te avise.

**Comment by LeandroBraier** [comment]
lo llamo a Valen y le digo.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Listo, ya agregue un disco de 50Gb y movi el contenido ahi.
Ya puede seguir subiendo el contenido. Capaz algo se le corrompio cuando se lleno el disco.

**Comment by mkreyness** [comment]
El CMS ahora anda normal

**Comment by LeandroBraier** [comment]
Ahora accedo al CMS pero no veo los usuarios cargados en el listado. Sin embargo, por FTP veo que están las carpetas y están "done". Qué habrá pasado?

**Comment by mkreyness** [comment]
las carpetas que tienen done son las viejas de prueba, todo eso lo borre de la base.
La unica carpeta util, que no se termino de subir, es la del dia 15, mientras no aparezca el archivo "participantes.txt", no se va a procesar, y ademas montones de videos estan con 0 bytes, señal de que se quedo sin disco cuando estaban subiendo. Alguno tambien debe estar por la mitad.

**Comment by LeandroBraier** [comment]
Perfecto, me quedo tranquilo entonces. Gracias!

**Comment by LeandroBraier** [comment]
@mkreyness y @valentinsabbath hoy ya mandé todos los mails del primer fin de semana y parece que la gente está entrando.

1) Podemos marcar de alguna manera (con un link propio por ejemplo, cosa que aparezca en analytics) a los que comparten o descargan el contenido? Necesito medir eso.

2) Ya está listo el segundo fin de semana para enviar?

**Comment by mkreyness** [comment]
todavia se estan subiendo videos de la 2da semana.
El sistema tenia previstas sus propias analytics, te acordas ? Lo extraia del log del servidor.
Solo que no lo veo funcionando, pero ahora reviso.
Voy a ver si del mismo log se puede sacar las descargas. Los "compartido" no, porque eso es un iframe provisto por FB, pero en facebook lo tenes que poder ver en las stats del app. Creo que estabas como co-developer ahi.

**Comment by ghost** [comment]
Si es por la subida, mi conexión sube a 100k 2,5 minutos por video aprox

**Comment by mkreyness** [comment]
100kbps, o sea 1MBps

**Comment by ghost** [comment]
exacto

**Comment by LeandroBraier** [comment]
Gracias @mkreyness ! La app es esta?

https://developers.facebook.com/apps/834490653330243/dashboard/

Recordaba lo de las visitas, gracias! Avisame si podés sumar lo de las descargas porfa.

**Comment by mkreyness** [comment]
Ahi procese lo del log, estaba que corriera a las 21:00, pero lo force ahora.
Si, ese es el app de facebook.
Ahora estoy viendo lo de las descargas.

**Comment by mkreyness** [comment]
Si, lo puedo detectar perfecto. Te puedo poner un tilde en la lista de visitas que diga si ESA visita lo descargó o no. Te sirve ?

**Comment by mkreyness** [comment]
Ya puse el tilde y lo procesé.
Tene en cuenta que esto se actualiza una vez por dia.
Los de facebook TAMBIEN los poder ver por el CMS, porque son accesos con referrer "facebook".
Si en la busqueda pones %facebook% (o en un filtrado que hagas en excel) los ves perfecto.

**Comment by LeandroBraier** [comment]
Excelente MK!!! Muchísimísimas gracias!! abrazo grande 

Mañana a la mañana agarro las bases para mandar. Por las dudas confirmenme cuando esté todo subido OK. abrazo a los dos

**Comment by mkreyness** [comment]
Valen ademas de esto que esta subiendo con fecha 27, tenes otra carpeta mas ?
Acordate renombrar esto como 2016-07-23 ANTES de subir el participantes.txt

**Comment by LeandroBraier** [comment]
Buen día muchachos!

Quedó al final? Puedo enviar o espero?

**Comment by ghost** [comment]
Lean se está subiendo el dia 24, a las 14 hs va a estas según el tiempo estimado

**Comment by LeandroBraier** [comment]
ok, perfecto. Confirmenme porfa.

**Comment by mkreyness** [comment]
Veo que se proceso, y sobraron unos cuantos archivos, que no venian en el participantes.txt
A ojo parece que ya habian venido en el dia 22.
Si podes chequear eso Valen (porque yo no estoy guardando backup por dia por el tema de espacio), me parece que estaria todo terminado de subir y procesar.

**Comment by ghost** [comment]
Correcto ya podés mandar los mails

**Comment by LeandroBraier** [comment]
Gracias Valen! abrazo a los dos!
