### ISSUE TITLE
Confirmación Analytics Paty Chile

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Paty#12]
Buenas noches @FAAREIA !

Le pusiste anaylitcs a la web nueva de Paty Chile?

Quise entrar a la cuenta de Benteveo Analytics que usamos siempre y veo 15 visitas del día de ayer, pero no estoy seguro si está bien puesto el tag. La campaña ya se lanzó en Facebook. Porfa si no está concretado el vínculo mañana a primera hora concretalo y confirmame.

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, no tengo el gmail de benteveo como para entrar y crear la cuenta. Me lo pasas? Y si los de Paty quieren que sea desde su cuenta, pasame la de ellos.

**Comment by LeandroBraier** [comment]
Buen día @FAAREIA ! No sé si hay que crear la cuenta porque ya está creada para ese dominio pero sí chequear que esté bien hecho el vinculo y no se haya "Desacomodado" con esta nueva landing.

El acceso:

benteveoanalytics@gmail.com
guatepeor5582

abrazo

**Comment by FAAREIA** [comment]
@mkreyness habría que pegar este código en los 3 htmls.

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-72368836-1', 'auto');
  ga('send', 'pageview');
</script>
```

**Comment by mkreyness** [comment]
ok, ya lo hago.

**Comment by mkreyness** [comment]
listo

**Comment by LeandroBraier** [comment]
Muchas gracias a los dos!!! Ya quedó todo rastreable entonces?

**Comment by LeandroBraier** [comment]
Solo confirmenme porfa. Necesito rastrear tanto las visitas a la HOME como a cada página de los videos de los usuarios.

**Comment by mkreyness** [comment]
Esta puesto, pero no tengo como verificarlo, vos podes entrar a la pagina de analytics y chequear si hay actividad, supongo.

**Comment by LeandroBraier** [comment]
Perfecto, chequeado. Gracias @mkreyness !

Consulta por las dudas: qué formato de video vamos a usar para los videos? Usemos el de la otra vez que se veía en todos los dispositivos y demás. Que no requiere java ni nada de eso no?

abrazo

**Comment by mkreyness** [comment]
Es .mp4, no requiere nada. En definitiva, el video es lo que ustedes pasaron, lo que hace el programa de Valentin es superponerle las fotos nada mas.
Igual me encantaria ver alguno... Tenes idea que pasa que todavia no subieron nada ?

**Comment by LeandroBraier** [comment]
La verdad no sé. Me dijo Eze que Valentín tenía que solucionar algo antes
de mandarlos. Consultale a él a ver qué te dice. Hoy teóricamente los
mandaban.

**Comment by mkreyness** [comment]
ahi le mande un mail avisando lo que te dije el otro dia de que apaguen el feature de upload simultaneo del programa que usen para subirlos.

**Comment by mkreyness** [comment]
Me dice que fue un desastre, no andaba nada del tracking y se le corrompian las fotos. Pasaron a un plan B y tiene que laburar con 5 fotos fijas nada mas a mano. Se lo deben haber querido comer crudo...

**Comment by LeandroBraier** [comment]
jajaja Me estaba contando Eze. Espero que no haya sido tan así. Igual lo
que entendí por Eze es que en el lugar se vieron fotos pero que en la
exportacion y envio de mails deberían ser videos como originalmente lo
imaginamos no? (aunque esto conlleve que yo testee uno por uno los videos y
veamos las coordenadas a ajustar).

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Si, por lo que yo entendi de lo que me escribio Valentin, el va a generar los videos de todos modos, y eso es lo que va a subirse. No deberia cambiar nada del lado del sitio.
