### ISSUE TITLE
Mailing Interno Lanzamiento Paty Chile

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Paty#13]
@FAAREIA me pidió el cliente que maquetemos un mailing interno para que ellos avisen internamente que se lanzó la campaña.

Tomá como base el diseño del mailing para los usuarios, pero usemos estas fotos que te adjunto acá:

[FOTOS PATY CHILE.zip](https://github.com/LeandroBraier/PatyChile/files/369200/FOTOS.PATY.CHILE.zip)

El texto sería el siguiente:

**¡Lanzamos con gran éxito la nueva campaña de Paty Chile!

Mirá las primeras fotos de la innovadora activación en shoppings de la nueva campaña "Entra a la Leyenda Paty" con el lanzamiento de Paty MEGA como centro. Además de probar el nuevo producto, los participantes se llevan un video personalizado de La Leyenda Paty en los que ellos son protagonistas junto a Rodrigo Salinas. 

Compartí nuestras comunicaciones en redes y sumate a este gran lanzamiento.**

(La frase final de "compartí" que linkee al facebook de Paty Chile: https://www.facebook.com/paty.chile )

abrazo

pd: dale prioridad a esto antes que a FUCA. SI podemos tenerlo para hoy genial. Sino para mañana a la mañana está bien.

**Comment by FAAREIA** [comment]
El encabezado con tiene esta imagen: http://benteveo.tv/mailing/paty-chile/img/entra-leyenda-paty.jpg
lo mantenemos no? Al igual que el footer

**Comment by LeandroBraier** [comment]
Si, tal cual. Header y footer iguales.

**Comment by FAAREIA** [comment]
Fijate ahi lea:
http://www.benteveo.tv/_paty-leyenda/leyenda-paty.html

**Comment by LeandroBraier** [comment]
Está buenisimo Fede!!! Solo te voy a cambiar algunas fotos ahora nomás, ya te las paso. Lo estoy viendo con Eze.

**Comment by LeandroBraier** [comment]
Acá van las fotos finales Fede!

Cambialas por estas fotos y estamos bien.

[Fotos Album Finales.zip](https://github.com/LeandroBraier/PatyChile/files/369907/Fotos.Album.Finales.zip)

**Comment by LeandroBraier** [comment]
Puede ser para mañana a la mañana todo bien.

**Comment by FAAREIA** [comment]
Fijate ahi Lea, dale F5

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA ! Excelente! Lo mando al cliente y te aviso.

**Comment by LeandroBraier** [comment]
@FAAREIA querido! Gustó mucho el mailing. Solo me pidieron los siguientes cambios:

1-      Sacar algunas imágenes de Shopping y poner algo de la activacion en cines que te pego acá:

<img width="1680" alt="activacion en cines 1" src="https://cloud.githubusercontent.com/assets/6719872/16998593/8c5ff606-4e90-11e6-88a6-d128dc3db982.png">
<img width="1680" alt="activacion en cines 2" src="https://cloud.githubusercontent.com/assets/6719872/16998870/b1d7c0ca-4e91-11e6-86fc-a9276de3c5b1.png">

2-      Cambiar la palabra "Mirá" por "Mira" y "Compartí" por "Comparte" para que sea en neutro.

3-      Agregar un Link al video de la campaña con un texto que diga: "Mira el spot de lanzamiento de "Entra a la Leyenda Paty".

https://www.youtube.com/watch?v=-8wQQCOfZQI

Con eso estamos.

abrazo

**Comment by FAAREIA** [comment]
http://www.benteveo.tv/_paty-leyenda/leyenda-paty.html

**Comment by LeandroBraier** [comment]
Muchas gracias @FAAREIA ! Quedó muy bien. Solo te pido que cambies la imagen de Salinas estirado en el cine, que no se entiende, por la que tenías antes ahí que creo era del Logo de Paty inflable en grande. Con la gente en las butacas ya se entiende lo del cine.

Con eso ya estamos.

abrazo

**Comment by FAAREIA** [comment]
Dale F5, ya la cambié

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA ! Excelente!!

abrazo grande

**Comment by LeandroBraier** [comment]
@FAAREIA me pide el cliente unos cambios más:

1) El texto de "Mira las primeras fotos" quedaría así:

“Mira las primeras fotos de la innovadora activación en shoppings de la nueva campaña "Entra a la Leyenda Paty" con el lanzamiento de Paty MEGA como centro. Además, desarrollamos una acción con la cadena Cinemark en tiempo real donde un espectador del cine interactúa con el comercial protagonizado por Rodrigo Salinas. ¡Empieza en la butaca y termina en la pantalla!.”

2) Las fotos me piden sacar estas dos fotos:

<img width="203" alt="captura de pantalla 2016-07-21 a las 6 33 23 p m" src="https://cloud.githubusercontent.com/assets/6719872/17038879/1e55f776-4f6e-11e6-8102-40a1710584fa.png">

<img width="169" alt="captura de pantalla 2016-07-21 a las 6 33 26 p m" src="https://cloud.githubusercontent.com/assets/6719872/17038883/2076abcc-4f6e-11e6-923e-2213367fb6f7.png">

3) Además, me piden agregar debajo de las fotos, una secuencia a través de un gif animado con el título de "ACTIVACIÓN EN CINES" que contenga una secuencia de las siguientes imágenes:

![image01](https://cloud.githubusercontent.com/assets/6719872/17042397/8e719e88-4f83-11e6-8df2-420de6d8c939.jpg)
![image02](https://cloud.githubusercontent.com/assets/6719872/17042403/9041afd2-4f83-11e6-9b75-0e7af58d08b0.jpg)
![image03](https://cloud.githubusercontent.com/assets/6719872/17042407/9287706a-4f83-11e6-8207-8f42c91f4db9.jpg)
![image04](https://cloud.githubusercontent.com/assets/6719872/17042409/94fc6ab2-4f83-11e6-896d-434f5a9dfa57.jpg)

abrazo

**Comment by FAAREIA** [comment]
Fijate ahi Lea:
http://www.benteveo.tv/_paty-leyenda/leyenda-paty.html

**Comment by LeandroBraier** [comment]
Muchas gracias @FAAREIA ! Quedó impecable! 

abrazo
