### ISSUE TITLE
Actualizacion Mapa en Landing Paty Chile URGENTE

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Paty#14]
@FAAREIA y @mkreyness necesito que urgente cambien el mapa y el texto de "Donde está la máquina de Paty?"

22 a 24/07 MALL PLAZA OESTE

Mapa:
`https://www.google.com.ar/maps/place/Mall+Plaza+Oeste/@-33.5172842,-70.7874751,12z/data=!4m18!1m12!4m11!1m3!2m2!1d-70.717094!2d-33.5099849!1m6!1m2!1s0x9662dca7419ab291:0xfebfebddff97232a!2sAv.+Am%C3%A9rico+Vespucio+1501,+Cerrillos,+Regi%C3%B3n+Metropolitana,+Chile!2m2!1d-70.717435!2d-33.5173039!3m4!1s0x9662dca7419ab291:0xfebfebddff97232a!8m2!3d-33.5173039!4d-70.717435`

Me confirman cuando está actualizado porfa?

abrazo

**Comment by mkreyness** [comment]
Lo tengo que hacer yo.

Necesito que me pases el embed del mapa como te dije el otro dia, no se puede poner eso y si lo hago yo me sale con el "como llegar".

**Comment by LeandroBraier** [comment]
Perdón, me olvidé de eso. Acá va con el embed:

`<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d106444.43106916116!2d-70.7874751!3d-33.5172842!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9662dca7419ab291%3A0xfebfebddff97232a!2sMall+Plaza+Oeste!5e0!3m2!1sen!2sar!4v1468856364028" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>`

**Comment by mkreyness** [comment]
listo, ya esta todo puesto.

**Comment by LeandroBraier** [comment]
Muchas gracias chicos!!

abrazo
