### ISSUE TITLE
Video en el servidor

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Paty#15]
@mkreyness vos podrías subir el video del spot de Paty al servidor de laleyendapaty.cl ?

https://www.wetransfer.com/downloads/14f25648418e741773b778335a8cd2b020160726152115/eb098b77d29a48d059c21e7d40e51b0220160726152115/7bc570

Es para que lo vean en la empresa porque adentro tienen baneado YouTube, Vimeo, Dropbox, etc.

Si se puede me lo subís y me pasás un link porfa?

**Comment by mkreyness** [comment]
Subiendo, te aviso cuando termine el URL definitivo.

**Comment by LeandroBraier** [comment]
Gracias MK!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
tarda horrores, seguramente porque estan subiendo tambien los de Valentin.

**Comment by mkreyness** [comment]
falta minimo media hora.

**Comment by LeandroBraier** [comment]
Ok, no problem MK. Gracias! Solo pasame el link cuando esté arriba.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
www.laleyendapaty.cl/videos/lanzamiento.mp4

**Comment by LeandroBraier** [comment]
Gracias Marce!! Hay forma de que tenga autorun?

Más allá de eso me doy cuenta que el principio la placa negra sería ideal sacarla. Es mucho lio subirlo de nuevo?

**Comment by LeandroBraier** [comment]
El video final sería este, perdón por el error MK:

https://www.wetransfer.com/downloads/ee540e0d409b62b7a0d6b1f6f2b8963420160726173337/00177c

Si lo puedo subir por FTP avisame y yo lo subo, todo bien. Confirmame si se puede poner con autorun porfa.

**Comment by mkreyness** [comment]
Ya lo estoy subiendo.
El archivo en si mismo no puede tener un autorun, eso es algo que sucede en el browser, no en server. Tendria que hacer una pagina donde ponerlo embedded en un tag de video.
Termino de subirlo y pruebo. El URL va a ser el mismo.

**Comment by mkreyness** [comment]
Me refiero al URL del video, obviamente la pagina tendria otro url.

**Comment by mkreyness** [comment]
Listo, nuevo y con autoplay:

http://www.laleyendapaty.cl/lanzamiento.html

**Comment by LeandroBraier** [comment]
Excelente! Gracias MK!!

**Comment by LeandroBraier** [comment]
Muy bueno!

**Comment by LeandroBraier** [comment]
@mkreyness un favorcito más te pido sobre esto.

La gente de BRF me dice que por la conexión lenta que tienen les reproduce muy lento el video. Podrás subir esta versión más comprimida de 10 mb manteniendo el link porfa?

https://www.wetransfer.com/downloads/9d7d692d4e16974fbfcbab4f4f630f5420160727180954/b2fe86

**Comment by mkreyness** [comment]
bajando, te aviso cuando este listo

**Comment by LeandroBraier** [comment]
Gracias @mkreyness !

**Comment by mkreyness** [comment]
listo, andando con la pagina de siempre. Queres que le agregue controles para que puedan pausar o rebobinar ?

**Comment by LeandroBraier** [comment]
Uuuuuuhh! Sería excelente MK!! Gracias!!!

**Comment by mkreyness** [comment]
listo

**Comment by LeandroBraier** [comment]
Muchas gracias @mkreyness !!! Lo veo bárbaro. abrazo grande
