### ISSUE TITLE
Apagamos el servidor de Paty Chile

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Paty#16]
@mkreyness el próximo lunes apagaríamos el servidor de Paty Chile, porque el domingo es el último día de la acción.

Agendatelo porfa.

abrazo

**Comment by mkreyness** [comment]
ok, lunes 15 al levantarme lo apago. Agendado.

**Comment by LeandroBraier** [comment]
Gracias MK!

**Comment by LeandroBraier** [comment]
@mkreyness antes de apagar, necesito backupear los videos. Son muchos o los tengo que seleccionar?

**Comment by mkreyness** [comment]
los videos los subio todos @valentinsabbath , asi que seguramente el ya los tiene en la maquina, y capaz esa maquina es la misma que esta en la oficina, porque ahi se proceso todo... Que te confirme Valen si los podes copiar directamente de ahi.

**Comment by LeandroBraier** [comment]
Genial. La maquetación de la web y los mailings está todo backupeado ahi
también?

2016-08-11 16:24 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
No, pero eso lo backupeo yo antes de apagarlo. Igual apagarlo NO es borrarlo. Capaz resucitamos ese servidor para benteveo en Amazon.

**Comment by LeandroBraier** [comment]
Ok, entiendo. De todas formas backupealo al sitio porfa y confirmame asi me quedo tranquilo. abrazo

**Comment by mkreyness** [comment]
Obvio, siempre lo hago antes de apagar, programas, datos y paginas.

**Comment by LeandroBraier** [comment]
Perfecto, gracias MK!!!

**Comment by LeandroBraier** [comment]
Me dice Valentin que en el servidor solo están las fotos y el programa para procesarlas, no los videos finales. Los podrás backupear también o preferís que seleccione?

Si es así mañana te paso lista, confirmame nomás.

**Comment by mkreyness** [comment]
Pero desde algun lado los subio, estan en el OTRO servidor ? No tiene sentido bajar 50Gb de video que costo tanto subir, no me digas que despues de subirlos los borró...

**Comment by LeandroBraier** [comment]
Me dice "después te explico". Ahi le estoy preguntando.

**Comment by LeandroBraier** [comment]
PArece que si.

**Comment by LeandroBraier** [comment]
No te preocupes, selecciono y te pido con numero de particpante unos 10. No pasa nada.

**Comment by mkreyness** [comment]
ok. Tiene "el delete facil" Valen...

**Comment by LeandroBraier** [comment]
jejej parece. Para la próxima le decimos. abrazo

**Comment by LeandroBraier** [comment]
Marce, te pido que me descargues estos 3 videos y otros 12 al azar porfa.

http://www.laleyendapaty.cl/video.html?numero=664442641984a4b91fd9fcb8a0adaa94a16b38ca

http://www.laleyendapaty.cl/video.html?numero=6e47c3fd2d5678e21e2d24178020dfba9ff50e81

http://www.laleyendapaty.cl/video.html?numero=891c6618bf7259e8df64533a116289b03250ba25

Con eso me arreglo. Mandamelo mañana o cuando puedas tranqui, mientras sea antes de apagar el servidor.

De todas formas el servidor no se borra no?

abrazo

**Comment by mkreyness** [comment]
no se borra, pero mantener los discos apagados ALGO cuesta.  Mi intencion es aprovecharlo para la migracion de Benteveo, y ahi va a haber que liberar espacio.
Esos que pusiste ahi, podes hacer el download con el link como cualquiera, para que los voy a bajar yo y pasartelos, si lo podes hacer directo ?
Si queres te paso 12 links mas al azar.

**Comment by LeandroBraier** [comment]
Jaja tenes razon que boludo !

No te preocupes.  Yo los bajo entonces.

Abrazo y gracias!

**Comment by LeandroBraier** [comment]
Adios Paty Cruel! Todo apagado no?

**Comment by mkreyness** [comment]
Si claro.
