### ISSUE TITLE
Newsletter Interno Paty Uruguay

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Paty#17]
@FAAREIA necesitaría que el lunes armes un newsletter similar al que hicimos para el lanzamiento de la campaña Paty Chile. Lo tenías alojado acá pero ya lo borramos del servidor:
http://www.benteveo.tv/_paty-leyenda/leyenda-paty.html

Te paso captura de lo que tengo guardado:

<img width="836" alt="captura de pantalla 2016-10-14 a las 6 05 05 p m" src="https://cloud.githubusercontent.com/assets/6719872/19402159/da769ac8-9235-11e6-8737-b460281e1898.png">

Lo que necesito que diga es:

TÍTULO: **Paty sigue conquistando…ahora Uruguay!**

TEXTO: **Siguiendo con la conquista de Latam, pensamos una acción a la medida de los uruguayos… ¡Y qué mejor embajador que Rubén Rada para hacerlo! Un genio que lleva su “sabiduría” a los asados uruguayos.**

IMAGEN: Ruben Rada mirando a cámara con toda la estética del Keyvisual de la acción, que te paso acá:

https://www.wetransfer.com/downloads/56b97515f9ccf087aafab540d1313fd820161014211438/afeddb2d6eef369f880b438573dc9ea220161014211438/9c8e54

Después viene un GIF del video que te paso acá:

![paty-spot-uruguay-final](https://cloud.githubusercontent.com/assets/6719872/19403951/e5426918-9240-11e6-95f6-360bd4e3a270.gif)

con link al video mismo (recordá que el video debe estar en el mismo servidor que el mailing (es decir, el nuestro de Benteveo) porque en la empresa no pueden acceder a YouTube.

[PATY_spot_rada_FINAL-redux.mp4.zip](https://github.com/LeandroBraier/Paty/files/530449/PATY_spot_rada_FINAL-redux.mp4.zip)

TEXTO: En los supermercados, Rubén Rada desde dentro de una heladera, invitaba a todos a participar por hermosos premios:
4 fotos:

a) Foto presentación de la heladera: https://scontent-eze1-1.xx.fbcdn.net/t31.0-8/14525200_558959574314419_8505388997723985994_o.jpg
b)       Foto heladera que se vea bien la imagen, con gente: 
https://scontent-eze1-1.xx.fbcdn.net/t31.0-8/14480640_555415594668817_7472519548391447493_o.jpg
c)      Foto de gente teniendo el ticket:
![img_1748](https://cloud.githubusercontent.com/assets/6719872/19404269/10354ef4-9243-11e6-833c-2a72a028c110.jpg)
d)       Foto con el regalo
https://scontent-eze1-1.xx.fbcdn.net/t31.0-8/14500246_555415588002151_2508496392504145609_o.jpg

TEXTO: **También fuimos a los lugares más emblemáticos de Uruguay con nuestro FoodTruck Paty…**

3 fotos
a)       Fotos en la feria bien lleno de gente degustando:

https://scontent-eze1-1.xx.fbcdn.net/t31.0-8/14480763_558017481075295_4311154077376249945_o.jpg

![img_1715](https://cloud.githubusercontent.com/assets/6719872/19404340/ae72f008-9243-11e6-963e-39c6ad57c925.jpg)

b)      Foto que se vea las promotoras lindas q pusimos:

https://scontent-eze1-1.xx.fbcdn.net/t31.0-8/14468640_555436494666727_5826354042844639527_o.jpg

TEXTO: **Y comunicamos todo...! Estuvimos en los principales programas de Uy, radio y carteles …. Hasta recorrimos Uruguay con un Bus Paty!**
LOGO DE TINELLI – BENDITA – ALMORZANDO – LOGO RADIOS – FOTOS DEL BUS PATY  (TE LOS PASO EL LUNES, PERO PODÉS IR USANDO ESTOS DE ACÁ:

http://www.logotypes101.com/logo/showmatch
https://4.bp.blogspot.com/-tAuuKbGenSM/V2Mx-7gezGI/AAAAAAAAqFg/gBXE51gFchsBAhZfGE_XB5yVy9w-xYV2QCLcB/s1600/BENDITA-noticias-programas.jpg
https://i.ytimg.com/vi/K2irxoAF2pM/maxresdefault.jpg

TEXTO: **Y por todo esto salimos en los principales noticieros**
LINK A ESTE VIDEO NOTICIERO: 
[Empresarial Paty Telemundo 30-9 Redux.mp4.zip](https://github.com/LeandroBraier/Paty/files/530450/Empresarial.Paty.Telemundo.30-9.Redux.mp4.zip)

TEXTO: **PATY Sigue conquistando!**

Confirmame si para el lunes a la tarde podríamos tenerlo. 

abrazo y buen finde!

**Comment by FAAREIA** [comment]
Hola Lea, estuve viendo lo del mailing. No creo que lleguemos para hoy, primero hay que diseñarlo y luego maquetarlo y adicionalmente preparar un HTML con el video que todavía no lo tengo.

**Comment by LeandroBraier** [comment]
Ok @FAAREIA ! Para mañana lo ves posible?

El video te lo pasé acá en el ticket. Todos los materiales están acá para armarlo, no te estoy debiendo nada. Confirmame si pudiste descargarlos. Ya están comprimidos a full.

**Comment by FAAREIA** [comment]
Para mañana, si el diseño sale derecho sin vueltas ni correcciones sobre cosas ya aprobadas, si podríamos tenerlo listo.
Ahi va el diseño:

![paty-uy](https://cloud.githubusercontent.com/assets/6184969/19443237/7f935aae-9462-11e6-84bf-bf372cc5ec23.jpg)

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA ! De composición está bien pero el keyvisual está mal. No es el keyvisual correcto, se ve que me mandaron mal ese PSD. No podés usar el segundo PSD que te pasé? El de la portada de Facebook? Esa estética si es la correcta. Sino avisame y te paso el keyvisual actualizado. abrazo

**Comment by FAAREIA** [comment]
Mandamelo actualizado asi lo veo. Igualmente solo aplicaría al header del mailing.

**Comment by LeandroBraier** [comment]
Si. En general solo en Header y Footer. Te estoy enviando en un ratito el editable de este afiche, que si tiene todo actualizado:

![afichevf112](https://cloud.githubusercontent.com/assets/6719872/19446801/db3940e0-9470-11e6-83bc-2226b1ef97fd.png)

En breve lo tengo.

abrazo

**Comment by FAAREIA** [comment]
No te olvides de esto lea, no puedo avanzar sino. Ni si quiera para armar el diseño que contiene el video.

**Comment by LeandroBraier** [comment]
@FAAREIA me dicen que en los PSD que tenés ya tenés todo para resolverlo. Simplemente cambiá la foto de Rada, las luces y todos los elementos que te pasamos en el PSD de la portada, para que el header del mail quede igual que el afiche que te pasé. 

Solo te va a faltar darle la estética del afiche a la frase PATY SIGUE CONQUISTANDO AHORA URUGUAY. Esa frase te la vamos a pasar diseñada en PNG transparente para que vos lo puedas pegar arriba.

Avisame si se entiende sino te llamo.

abrazo

**Comment by FAAREIA** [comment]
Si se entiende, igual ya estuve avanzando como pude. Mañana lo terminamos seguro

**Comment by LeandroBraier** [comment]
Genial! Acá te paso el PNG transparente. Decime si te sirve en este tamaño.

![paty-sigue-conquistando](https://cloud.githubusercontent.com/assets/6719872/19484470/14bd44f2-952e-11e6-8215-6a61d300d6a7.png)

 Sino tengo el PSD acá: https://mega.nz/#!rt8mxC6Y!18uNDBzVk_TQgp3kJ0vv4ifoYvhVOLiadL7j8n_VW7A

**Comment by LeandroBraier** [comment]
@FAAREIA te paso los logos de los programas de TV, para que reemplaces los que te pasé provisorios. Nos faltaría el de ALMORZANDO y las fotos del BUS de PATY.

[Imagenes Newsletter Uruguay.zip](https://github.com/LeandroBraier/Paty/files/536979/Imagenes.Newsletter.Uruguay.zip)

abrazo

**Comment by FAAREIA** [comment]
Fijate ahi Lea:
http://www.benteveo.tv/paty_uy/mailing/interno/ruben-rada.html

**Comment by LeandroBraier** [comment]
Excelente @FAAREIA ! Está quedando genial. Te pido solo algunos detalles:

1) Se le puede agregar las lucecitas alrededor de los distintos marcos que hay? Me refiero al GIF animado del spot y a los albumes de fotos.

2) Necesitaría agregar al GIF animado una leyenda que diga: MIRÁ EL SPOT DE CAMPAÑA.

3) Ajuste de texto 1:
Donde dice:
Y COMUNICAMOS TODO...! ESTUVIMOS EN LOS PRINCIPALES PROGRAMAS DE UY, RADIO Y CARTELES... HASTA RECORRIMOS URUGUAY CON UN BUS PATY! 
Debe decir:
Y COMUNICAMOS TODO...! ESTUVIMOS EN LOS PRINCIPALES PROGRAMAS DE TV, RADIO Y ESPACIOS EN VÍA PÚBLICA... HASTA RECORRIMOS URUGUAY CON UN BUS PATY!

4) Ajuste de texto 2: 
Donde dice:
Y POR TODO ESTO SALIMOS EN LOS PRINCIPALES NOTICIEROS MIRA EL VIDEO
Debería deicr
Y POR TODO ESTO SALIMOS EN LOS PRINCIPALES NOTICIEROS. MIRÁ EL VIDEO!

Además de estos puntos, estoy esperando que me pasen las fotos del BUS PATY para incluir debajo de los íconos de los programas de TV y radio, pero mientras no lo tengamos sigamos con el mailing así. Si podés ajustar esto hoy genial, asi mando una versión previa y prueban los videos.

abrazo y gracias!

**Comment by FAAREIA** [comment]
Ahi estan listos los cambios, creo que no me faltó nada.
Cualquier otra cosa decime

**Comment by LeandroBraier** [comment]
Buenisimo @FAAREIA ! Solo te faltó el punto 2. Agregar el texto MIRÁ EL VIDEO arriba del gif animado del spot. Con eso lo mando.

Gracias!

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Perfecto @FAAREIA ! Gracias!

Te avisoc uando tengo feedback o las fotos del bus.

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA nos aprobaron un diseño que hicimos con el diseñador. Te paso el PSD así lo ponés todo como fragmento de imagenes, como hacíamos antes.

No nos importa que a alguien le vayan al spam, es un mail interno. Resolvelo lo más simple que puedas y sacatelo de encima. No le des demasiado bola. Lo necesitamos para el viernes así que dale prioridad porfa.

PSD en:
https://mega.nz/#!mss3lDZb!Lo6nB6CW8drUEOVPKzi5lwSq4LSMdX0DgH8eTdzl33w

abrazo

**Comment by FAAREIA** [comment]
http://www.benteveo.tv/paty_uy/mailing/interno/ruben-rada.html

**Comment by LeandroBraier** [comment]
Está casi perfecto. El segundo GIF no se reproduce. Se ve solo las 2
promotoras fijo, pero era un gif con muchisimas fotos.  Cambiá eso y
estamos.

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Muchas gracias Fede!! abrazo grand

**Comment by LeandroBraier** [comment]
@FAAREIA cuando lo subí a mailchimp y lo mandé, al cliente se le partió todo el mail. Dice que se descentralizaron algunas partes. Podrás entrar a mail chimp/ templates y ver si se puede corregir eso? Yo lo veo bien en gmail pero ellos lo deben ver así en algun otro cliente de mail.

**Comment by FAAREIA** [comment]
Me voy a fijar en mailchimp pero es muy raro que se haya roto porque no tiene nada especial en ninguna parte, son solo imágenes. Si no encuentro errores, necesito ver al menos un screenshot de como lo ven. Te aviso

**Comment by FAAREIA** [comment]
Ahi le toqué 1 sola cosa, prueben. Si se sigue viendo mal, que manden screenshot y versión del programa que usan. No debería de verse mal en ningun cliente de email

**Comment by LeandroBraier** [comment]
Muchas gracias Fede!! Te cuento: yo lo vi bien. El cliente dijo que l veía mal y reenvió el mailing que recibió. Te paso acá screenshot:

<img width="1132" alt="captura de pantalla 2016-10-28 a las 4 22 01 p m" src="https://cloud.githubusercontent.com/assets/6719872/19818564/a89ed44c-9d26-11e6-8780-baeb06c40808.png">

Me confirmás porfa si con lo que ajustaste esto se resuelve?

**Comment by FAAREIA** [comment]
Fijate ahora lea

**Comment by LeandroBraier** [comment]
Le modificaste algo mas?

**Comment by FAAREIA** [comment]
Si, probalo que tiene que ir bien

**Comment by LeandroBraier** [comment]
Gracias Fede!!! abrazo grande!

**Comment by LeandroBraier** [comment]
@FAAREIA el cliente abre el mailing en Outlook y me dice que no ve los GIF activos. Te fijás qué puede ser?

Te paso qué versión de Outlook es:

<img width="449" alt="captura de pantalla 2016-10-31 a las 12 18 55 p m" src="https://cloud.githubusercontent.com/assets/6719872/19858580/c81dc792-9f60-11e6-8805-c8b470cf84d8.png">

Espero tu respuesta lo antes posible.

abrazo

**Comment by FAAREIA** [comment]
No me sorprende los correos estan muy limitados.
Te paso lo que lei en la página oficial de miscrosoft

> Any type of inserted animation (whether GIF or video) hasn't been supported in the Outlook <desktop email client> since OL'2007. To be more specific, animations are not displayed when viewing a message in the desktop client - doesn't matter what the <email account> is - whether Outlook.com or any other. Animated GIFs simply appear as a static image at best with a message.

Si el tipo quiere ver el gif, puede probar lo siguiente:

> To play animated GIF files, you must open the files in the Preview/Properties window. To do this, select the animated GIF file, and then on the View menu, click Preview/Properties.

**Comment by LeandroBraier** [comment]
Ufff... qué bajón!

Te voy a tener que pedir una versión en que las fotos del GIF estén
desplegadas todas entonces, como era antes. Como un album. Llegás para hoy?

**Comment by FAAREIA** [comment]
No hoy ya hice las 4hs entre lo de siguit y el news =/
Mañana a la mañana lo liquidamos y si podes pasame como quieren que se vean las fotos desplegadas o como el diseño va a cambiar ahora que tiene las fotos desplegadas.

**Comment by FAAREIA** [comment]
Lea también pensá que el link que se incluye en los mailings para ver la versión online, sirve para esto mismo, para evadir todas las trabas de los clientes de correo y ver el mailing en versión "full"
No sería una mala opción para evitar tanto lio con el gif

**Comment by LeandroBraier** [comment]
Claro, entiendo. Les digo eso y te aviso qué me dicen.

Las fotos deberían verse como en la primer versión que hiciste vos, te
acordás? Donde están distribuidas en un espacio rectangular.

Consulto y te digo.

abrazo

2016-10-31 12:32 GMT-03:00 Federico Arena notifications@github.com:

**Comment by LeandroBraier** [comment]
Fede podemos intentar mañana meter los gifs como videos?

Aca dice que se puede para outlook:

http://blog.es.mailify.com/envio-emailing/poner-un-video-de-youtube-en-un-mailing-masivo/

**Comment by FAAREIA** [comment]
No se puede eso, meter un verdadero video para que se reproduzca ahi mismo en el cliente de correo no es posible. De hecho el artículo dice eso mismo:

> De esta forma el usuario clicará sobre la imagen pensando que se activará el vídeo pero simplemente le llevará a la página de YouTube en la que está el vídeo colgado.

Esta solución es lo mismo que tener un gif sin animarse =/

**Comment by FAAREIA** [comment]
Ahi vi bien la solución que vos decis, pero no se puede controlar en cómo y donde aparece el video.
Probalo con la versión nueva que subí a ver como sale y si sale...

**Comment by LeandroBraier** [comment]
Decís en Mailchimp? Ya lo subiste en el template de Mailchimp?

**Comment by LeandroBraier** [comment]
No sé donde mirarlo.

**Comment by FAAREIA** [comment]
Pasame el código por whatsapp que lo meto en mailchimp

**Comment by LeandroBraier** [comment]
Pará. Me acabo de acordar que igualmente por seguridad informática ellos no pueden acceder a YouTube. Olvidate.

No me respondieron pero avancemos con el album de fotos directamente. Disponé un rectángulo ahí con las fotos que tenemos distribuidas y listo. Así no perdemos más tiempo.

Lo del video igual nos va a servir para otro mailing de VIE TUR que está en camino.

abrazo

**Comment by FAAREIA** [comment]
Fijate ahi lea

**Comment by LeandroBraier** [comment]
En donde lo veo Fede? Ni en link ni en mailchimp veo los cambios.

**Comment by FAAREIA** [comment]
Lo hice sobre Mailing Resumen Paty Uruguay (copy 01)

**Comment by LeandroBraier** [comment]
@FAAREIA estás? No veo los cambios.

**Comment by LeandroBraier** [comment]
Ahora si, perdón! No había visto tu ultimo mensaje.

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA me piden una modificación pequeña nomás. Cambiar la foto donde se ve al canoso por la foto de Rada, como dice acá:

<img width="541" alt="captura de pantalla 2016-11-01 a las 3 53 09 p m" src="https://cloud.githubusercontent.com/assets/6719872/19901840/400231bc-a047-11e6-8a70-aa37e0d1a581.png">

Me avisás cuando puedas tenerlo ajustado? Pedime el codigo de mailchimp si necesitás.

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Muchas gracias @FAAREIA ! abrazo grande
