### ISSUE TITLE
Boton Descargar Video + Mailing de Aprovechá a descargar tu video 22-02

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Paty#3]
@mkreyness y @FAAREIA necesitamos implementar esto para Paty Chile como lo implementamos para la maratón (adaptando la estética, obvio).

Necesito:
1. Un botón como este:
   http://www.parexklaukol.com.ar/maraton/videoTdescarga.html?numero=1818
   https://github.com/LeandroBraier/Klaukol/issues/190
2.  Un mailing como este:
   http://www.parexklaukol.com.ar/_mailing/maraton/maraton-video.html
   https://github.com/LeandroBraier/Klaukol/issues/191

El texto del mailing sería:

Hola XXXXXX!

¿Ya viste tu video subido a La Leyenda Paty?
Ahora ya podés descargarlo a tu computadora. Aprovechá esta semana que es la última semana de vigencia de la campaña.

abrazo

**Comment by mkreyness** [comment]
ojo el mailing en este caso saldria de MailChimp, asi que hay que hacerlo como el template de MailChimp que ya hay, y lo reenviarias a toda la base ?

**Comment by LeandroBraier** [comment]
Exacto MK.

**Comment by FAAREIA** [comment]
Marce, podrían indicarme cuál template es? Asi voy metiendo mano en lo del botón.
Pasenme por mail usuario y clave también que no los tengo anotados

Gracias
Abrazo

**Comment by mkreyness** [comment]
Creo que hay 2 user templates en total, el que diga algo de laleyendapaty.
Pero no tenes que cambiar ese, tenes que hacer uno similar.
User/pass no alcanza, tenes que tener un codigo de autenticacion que solo te lo puede pasar en el momento Ezequiel.

**Comment by FAAREIA** [comment]
O_O
Todo eso para meterme y duplicar/modificar un template?

**Comment by mkreyness** [comment]
Asi es mailchimp.

**Comment by LeandroBraier** [comment]
El código de autenticación pediselo a Eze por whatsapp y decile que estás
atento esperándolo. Él te lo va a pasar al toque y tené 45 segundos para
completarlo jeje

Lo hicimos por seguridad y para ahorrar unos mangos y ahora nos resulta un
engorro la verdad.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
PErfecto, mañana a la mañana se lo pido y veo este tema.

**Comment by FAAREIA** [comment]
Ahi ya pude crear un nuevo template en base al anterior de Paty Chile. Pueden verlo en mailchimp, se llama: "La Leyenda Paty - Descargá tu video"

**Comment by LeandroBraier** [comment]
Me gusta @FAAREIA ! Lo único: se podrá agregar el GIF animado de vuelta? Solo para saber. Quizá es mejor que no para que pase mejor el filtro del spam, pero al menos debería tener un link al video claro, más allá del botón de descarga.

**Comment by FAAREIA** [comment]
Si se puede agregar un gif. El gif sería sobre el video propio de cada uno o uno genérico? La primer idea me parece medio compleja

**Comment by LeandroBraier** [comment]
Fede, fijate el template que estamos usando para el primer envio de los
videos: cada usuario ya tiene asignado un GIF de su propio video en su
propia lista. Hablalo con MK porfa.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-02-19 12:32 GMT-03:00 Federico Arena notifications@github.com:

**Comment by mkreyness** [comment]
El template solo tiene que tener las variables que se llaman MMERGE3 y MMERGE4. Una tiene la direccion del GIF y la otra de la pagina que tiene el video.
En realidad lo del boton para descargar lo deberiamos agregar en la pagina que tiene el video, porque si no habria que modificar la base de datos en MailChimp y no me parece que valga la pena.
Vas a ver que las variables se ponen entre unos marcadores asi: _|MMERGE3|_   _|MMERGE4|_

**Comment by mkreyness** [comment]
aca me modifico lo que escribi, lo quoteo:

`*|MMERGE3|*` 
`*|MMERGE4|*`

**Comment by LeandroBraier** [comment]
Buen día chicos! Esto debería estar para hoy, no solo el mailing sino el ajustes en la página del video. Me avisan por favor? abrazo

**Comment by mkreyness** [comment]
No recibi maqueta de los cambios en la pagina del video, en cuanto la reciba supongo que sera muy sencillo el cambio.
Acordate @FAAREIA que esto esta en laleyendapaty.cl, lo que pases ahi me tenes que avisar donde lo dejaste/como se llama para que yo lo tome y lo pase a produccion.

**Comment by FAAREIA** [comment]
La maqueta no sería la de mailchimp? Tengo que terminar de agregar eso aún

**Comment by LeandroBraier** [comment]
Mailchimp es el mailing. La página del video está en la web. Son dos html
distintos.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-02-22 9:23 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
En la página del video hay que agregar un botón de descargar video o solo en el mailing?

**Comment by mkreyness** [comment]
Es en la pagina, y en realidad el boton solo tiene que tener repetido el link del video que ya esta mas arriba en la pagina, es trivial.

**Comment by FAAREIA** [comment]
Maqueta del video a la cual solamente le agregué el botón para descargar el video
http://www.laleyendapaty.cl/previo2/video.html

Nombre del template de mailchimp:
La Leyenda Paty - Descargá tu video

En su momento mis pruebas las hice sobre el template original del video de paty chile y lo que no me percaté es que no solo se actualizaba la maqueta sino que mailchimp auto-guarda en el momento todo cambio que hagas por lo que el template se perdió. Se puede rehacer si tienen algun mail de prueba que hayan hecho en su momento, pero diganme si lo rehacemos o no.

**Comment by LeandroBraier** [comment]
Yo lo veo OK a la maqueta del video.

En cuanto al template de mailing hablenlo con MK, yo no sé bien a qué te
referís.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-02-22 10:12 GMT-03:00 Federico Arena notifications@github.com:

**Comment by mkreyness** [comment]
Lo que dice @FAAREIA  es que se perdio el template para el envio "normal" de mailings, pero eso igual entiendo que ya no se usaria mas, o si ?

Voy poniendo en produccion entonces esta nueva maqueta del video, ok ?

**Comment by mkreyness** [comment]
@FAAREIA ojo que hace rato que las modificaciones se vinieron haciendo sobre lo que estaba en previo3, no en previo2.
Podras volver a hacerlo sobre la version que esta en previo3 ?
Si no me temo que hay otras cosas que van a volver para atras (yo uso directo los CSS de previo3, y vos esto lo agregaste en el CSS de previo2).

**Comment by FAAREIA** [comment]
Ok, lo agrego ahi y pegó el código del botón por aca

**Comment by LeandroBraier** [comment]
Chicos, lamentablemente necesito tener los dos. Si no podemos tener los dos, vamos a tener que modificar el texto del template nuevo, porque da cuenta como que la persona ya vio el video. 

Para definir, les pido lo siguiente:

1) Dejen funcional este nuevo template.

2) Repongan el template anterior pero agregándole el botón de descargar video, tanto en el mailing como en la página del video. Todo igual pero con el botón de descargar video.

De esta forma le puedo enviar el mailing a los que nunca recibieron (por ejemplo, los de este último fin de semana) y también reenviarle a los que ya lo recibieron.

abrazo

**Comment by FAAREIA** [comment]
Marce ahi ya puse todo en `previo3`. El código del botón ya esta aplicado al template y es
`<a class="bajar-video" href="#" download><svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 24 24"><path d="M15,10h4l-7,8l-7-8h4V0h6V10z M18.2,1.8L17,3.4c3,1.7,5,5,5,8.6c0,5.5-4.5,10-10,10S2,17.5,2,12c0-3.7,2-6.9,5-8.6L5.8,1.8C2.3,3.9,0,7.7,0,12c0,6.6,5.4,12,12,12s12-5.4,12-12C24,7.7,21.7,3.9,18.2,1.8z"/></svg> Descargar mi video!</a>`

Por otra parte, para reponer el template anterior, necesitaría que me pasen un mail que tenga el template ese, asi lo copio.

**Comment by LeandroBraier** [comment]
Ahi te lo mandé Fede!

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-02-23 9:14 GMT-03:00 Federico Arena notifications@github.com:

**Comment by mkreyness** [comment]
Espera, que no entiendo.
Estas usando la palabra "template" para referirte a dos cosas diferentes ?
En el template DE MAILCHIMP no puede haber un boton de descarga, ahi solo esta el link para entrar a la pagina de laleyendapaty.cl, al mismo URL de siempre, al cual YO le tengo que agregar el boton basandome en tu MAQUETA (no es un template).

**Comment by mkreyness** [comment]
Asi quedaria la pagina a la que accederian (si estan todos de acuerdo que esta bien, solo tengo que cambiar el nombre de "videonuevo.html" por "video.html"

http://www.laleyendapaty.cl/nuevovideo.html?numero=c3ec0695b33e10e15bfa31f4a7b468ae4e063c95

**Comment by FAAREIA** [comment]
Lo veo perfecto. Ahi iría el botón de "descarga tu video" del template de mailchimp

**Comment by FAAREIA** [comment]
Ahi ya repuse el template que había sobreescrito por error.
Si pueden chequeenlo y pruebenlo. Marce las variables que usé son `*|FNAME|*` `*|MMERGE4|*` `*|MMERGE3|*`

Abrazo

**Comment by LeandroBraier** [comment]
Buen día @FAAREIA y @mkreyness 

Recién les envié un mail de prueba con el nuevo template y no funcionó. Tampoco el viejo recuperado por Fede. Por favor necesito que solucionen esto urgente porque estoy demorado con los envíos. No andan los gifs animados y no anda el dato del nombre de la persona.

Por suerte anda el link al video, pero aún no veo aplicado el botón de descargar online, eso creo que quedó de parte mia. Lo probé y está OK, subanlo por favor.

Esto es prioridad.

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, es probable que Marce tenga que hacer funcionar las variables en el nuevo template y reponer las variables en el viejo template. Ésto último me parece raro porque son las mismas que el me había dicho que use, pero anda a saber mailchimp como lo toma.

**Comment by LeandroBraier** [comment]
Ok. Por favor lo necesitp urgente.

**Comment by FAAREIA** [comment]
Lea, marce me dijo que hasta la 1 esta en una reunion.

**Comment by LeandroBraier** [comment]
Ok, apenas puedan.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
@FAAREIA y @mkreyness lamentablemente no funcionan bien los templates.

Acabo de tirar una prueba de cada uno de los mailings en Mailchimp **(la próxima necesito que uds hagan esto antes de entregarme el pedido terminado, para asegurarse de que lo entregado funciona bien)**.

Esto es lo que me sale en el primer template.

<img width="852" alt="captura de pantalla 2016-02-26 a las 11 27 13 a m" src="https://cloud.githubusercontent.com/assets/6719872/13354435/ca207350-dc79-11e5-9880-b54391382a66.png">

El segundo todavía ni me llegó pero a uds les envié copias también. Por favor revisenlo, hagan las pruebas que necesiten.

Esto necesitamos resolverlo URGENTE.

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA y @mkreyness lamentablemente no funcionan bien los templates.

Acabo de tirar una prueba de cada uno de los mailings en Mailchimp **(la próxima necesito que uds hagan esto antes de entregarme el pedido terminado, para asegurarse de que lo entregado funciona bien)**.

Esto es lo que me sale en el primer template.

<img width="852" alt="captura de pantalla 2016-02-26 a las 11 27 13 a m" src="https://cloud.githubusercontent.com/assets/6719872/13354435/ca207350-dc79-11e5-9880-b54391382a66.png">

<img width="665" alt="captura de pantalla 2016-02-26 a las 11 44 58 a m" src="https://cloud.githubusercontent.com/assets/6719872/13354731/a004909a-dc7b-11e5-96fb-57a09fb89a83.png">

Les envié copias también. Por favor revisenlo, hagan las pruebas que necesiten.

Esto necesitamos resolverlo URGENTE.

abrazo

**Comment by FAAREIA** [comment]
Intenté crear una campaña con una lista de un único suscriptor pero desconozco como cargar esas variables a cada suscriptor.
Por lo que se ve desde aca, la url del gif seguro tiene alguna comilla doble ( " ) en algun lado y rompe la foto.
¿Cual es la lista que estas usando de prueba y desde donde se pueden ver las variables de link e imagen?

**Comment by mkreyness** [comment]
No, el URL no tiene ninguna comilla.
El problema es que esta insertando dos veces el tag de imagen, vos no tenes que ponerlo, eso lo maneja solo mailchimp. El asunto es que como se perdio el template original es dificil reconstruilrlo ahora, pero la "imagen" es un tipo de objeto para mailchimp y el dato es solo el URL, no hay que poner uno en el template el tag de `<img ...`
Yo ahora estoy sin authenticator, si vos podes entrar Fede fijate esto que te digo.

**Comment by FAAREIA** [comment]
Ahi apliqué lo que dice marce, la variable `*|MMERGE3|*` quedó suelta dentro del anchor.
Hace un prueba que ahora debería llegar bien

**Comment by LeandroBraier** [comment]
Gracias! Ahi volví a enviar las pruebas. Veamos ahora.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-02-26 12:44 GMT-03:00 Federico Arena notifications@github.com:

**Comment by mkreyness** [comment]
El que me llego a mi estaba perfecto.

**Comment by LeandroBraier** [comment]
Yo los veo bien, solo que no entiendo por qué el de Descargar el video no
tiene puesto el marquito rústico de fondo. Lo podemos poner rápido asi ya
mando? O lleva mucho tiempo @FAAREIA  ?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Hola Lea, queres lo que lo agregue?
Lo rustico esta más pensado como fondo y no como botón, el mismo concepto fue aplicado al micrositio en su momento.
Avisame

**Comment by LeandroBraier** [comment]
No te preocupes Fede. Ya programe los mailings, es un detalle nomás.  Abrazo
