### ISSUE TITLE
Testing Paty Chile

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Paty#4]
@mkreyness y @valentinsabbath les paso acá el pedido de testing que ya tenemos en proceso:

A TESTEAR

1) Agregar un chroma y hacer capturas de referencia para probar. 

2) Ver si podemos conseguir el path del motion tracking del after. Le podemos preguntar a Marino. Sino pasarlo manual frame por frame: valores: X, Y, ángulo y zoom. 

Por ahora solo encontramos este link donde se da referencia de pixels en X e Y:
http://blog.grifo.tv/2010/08/12/motion-tracking/

!!! SPECS DE HARDWARE PARA VER QUÉ FALTA COMPRAR

Qué cámara usar, si se puede usar las mismas de Paty Chile

**Comment by mkreyness** [comment]
ya tengo andando como sacar el fondo verde, el problema es croppear adecuadamente. Las cosas automaticas fallan bastante. Adjunto foto cortada y croppeada (mal).
![cabeza-cropped](https://cloud.githubusercontent.com/assets/6135791/15875599/2389c8be-2cdf-11e6-853d-32fe10073613.png)

capaz aca no se ve porque el fondo es transparente y el fondo de github es blanco, pero tiene bastante espacio de mas a la izquierda del tipo (derecha nuestra). Obvio esto va a depender de cada foto, lo mejor seria saber que el espacio de la cabeza esta dentro de un marco fijo (dado por la posicion de la camara y el agujero).

**Comment by ghost** [comment]
Con qué la estás trimeando?

Yo lo estoy haciendo con esto y es  bastante efectivo:
mogrify -trim *.png

**Comment by ghost** [comment]
![3](https://cloud.githubusercontent.com/assets/16599421/15875719/d12c4c44-2cdf-11e6-94b9-f3598da3aec7.jpg)

![3](https://cloud.githubusercontent.com/assets/16599421/15875716/ca9b2a58-2cdf-11e6-8b41-8d7e2e2eeb8d.png)

**Comment by mkreyness** [comment]
con lo mismo que vos, pero es cuestion de suerte de cuan pulcra sea la imagen, fijate ademas que a tu chica le quedaron reflejos verdes en el pelo, no hay solucion perfecta.

**Comment by ghost** [comment]
Se podría suavizar el reborde con el imagemagick, no?

**Comment by mkreyness** [comment]
suavizar en que sentido ? Se le pueden sacar unos pixels pero eso tambien puede comer de mas (pelo, orejas).

**Comment by ghost** [comment]
Se le puede poner un sombreado

**Comment by mkreyness** [comment]
si es que el borde fue bien levantado, pero anda a saber, el problema es que tiene que ser todo automatico. Esperemos a ver si lo basico funciona con filmaciones reales antes de agregarle chiches.

**Comment by LeandroBraier** [comment]
@mkreyness y @valentinsabbath les subo acá el excel con los parámetros de posición y rotación de los primeros 12 segundos del video. Diganme si les sirve así o qué necesitarían diferente. Los de scale los podemos obtener también, solo que en estos 12 segundos no había variaciones.

[Script Trackeo Nahuel- Posicion y Rotacion primeros 12 segundos.xlsx](https://github.com/LeandroBraier/PatyChile/files/307585/Script.Trackeo.Nahuel-.Posicion.y.Rotacion.primeros.12.segundos.xlsx)

Más tarde les paso el excel con todo el video completo y scale.

Les paso también la carita sola recortada por el realizador para que tengan la referencia exacta y salvemos las diferencias que pueda haber con el recorte de ustedes.

![carita para trackear con alpha_00786](https://cloud.githubusercontent.com/assets/6719872/15939552/92cf07a0-2e4e-11e6-8c6e-6be780c3c144.png)

**Comment by mkreyness** [comment]
En realidad más importante que si hay variación o no es saber el grado de escala que representa respecto de la foto, que sería el 100%

**Comment by LeandroBraier** [comment]
Exacto MK.

**Comment by mkreyness** [comment]
Esperaba un porcentaje como respuesta. Vos decís que escaparon LA FOTO a que sea el 100% de la del video? Eso en la práctica no nos dice nada, lo que necesito saber es respecto de una foto real tomada a la distancia real, la cabeza esta es una cualquiera de stock.

**Comment by mkreyness** [comment]
donde dice "escaparon" lease "escalaron, maldito corrector".
Respecto del Excel: 
- algunas coordenadas tienen coma y otras tienen punto, esto lo hicieron a mano o sale asi del aftereffects ?
- la rotacion no la entiendo, no puede ser un angulo ? O que cuenta habria que hacer para convertir esos pixels en un angulo ?

**Comment by mkreyness** [comment]
Inclusive en un contexto en el cual la escala sube o baja, hablar de pixels de rotacion es una complicacion tremenda. En cambio el angulo no varia.

**Comment by mkreyness** [comment]
@LeandroBraier hay algun otro thread del proyecto patychile aparte de este ? Quiero anotar unos issues que tenemos que empezar a mover (hosting Amazon, envio de mailings)

**Comment by valentinsabbath** [comment]
@LeandroBraier voy a intentarlo

**Comment by LeandroBraier** [comment]
@mkreyness probemos de a una cosa por vez. 

TESTING DE HOY
Lo que quiere Eze que prueben ahora es si pueden hacer de forma automática que esta cabeza de stock trackee en este video. Tampoco el video es definitivo, así que va a haber un testing más fiel a la activación.

EXPORT DE DATOS
Lo que te mandé es lo que nos da el after. Son números de pixeles, no coordenadas como las conocemos. Si no les sirve esta info vamos a tener que buscar otra forma de trackear, pero los programas de post de imagen toman esto.

Entiendo que los puntos y comas son lo mismo, solo que al pasar la data al excel hace esa modificación. Acá te paso el archivo original que extrajimos de after:

[Script trackeo nahuel.txt](https://github.com/LeandroBraier/PatyChile/files/307939/Script.trackeo.nahuel.txt)

Como verás, es muchísimo más complejo porque el tracking se hace a partir de varios puntos específicos de la cara. Cuando hagamos el testing 2.0 el actor va a tener 4 cruces en la cara y va a ser más sencillo. Yo te pasé de los primeros 12 segundos, los 3 puntos que usa el realizador para trackear POSICIÓN (Nose Tip) y ROTACIÓN (Mouth Left y Mouth Right). El SCALE es como vos decís: el PNG transparente con la cara del pibe en el centro es el 100% del tamaño del video.

**Comment by mkreyness** [comment]
"OTROS THREADS"
no ni idea si yo puedo, preguntaba si habia algun otro porque capaz hay y no estoy copiado.
Yo queria empezar a hablar del hosting porque los videos se tienen que hostear para poder mandarlos por mail, y a su vez el mailing la vez pasada lo habiamos hecho via mailchimp, entonces tengo que poner una interface para descargarlos, etc.  En definitiva del hosting SI tengo backup de todo, aunque obviamente no es tan complicado como antes lo que hay que hacer si SOLO es mandar mails.

**Comment by mkreyness** [comment]
"TESTING DE HOY"
@valentinsabbath lo intentas vos ? O lo hago yo ? No dupliquemos laburo.
Por el archivo que mandaste me parece que es mas util medir el slope entre "right cheek" y "left cheek" que estan mas alejadas entre si que los extremos de la boca, y que capaz el actor este hablando o haciendo morisquetas y puede alterarlo.
Fijate @valentinsabbath con esos puntos si haciendo una simple cuenta entre (x1,y1) y (x2,y2)  obtenes un angulo y esa es la rotacion que hay que aplicar (con el convert del imagemagick supongo) a la cara antes de pegarla en el frame correspondiente.

**Comment by mkreyness** [comment]
Y esta bien pixels para trackear el centro, para pegar una imagen en un frame, igual tenemos que hablar en pixels.

**Comment by LeandroBraier** [comment]
"OTROS THREADS"

Creo un ticket aparte con este pedido por el hosting y cierro los comments al respecto.

**Comment by ghost** [comment]
Me habia equivocado de hilo, pero si, yo lo pruebo.

**Comment by mkreyness** [comment]
@valentinsabbath, el rotate es trivial:

convert -rotate ANGULO original_file.jpg new_file.jpg

ANGULO = arcotangente(y2-y1/x2-y1) \* 100 
creo. Donde (x2,y2) es la mejilla derecha y (x1,y1) es la mejilla izquierda.
Hay que tener en cuenta 2 cosas: 
-deberiamos tener la imagen cortada en un CUADRADO para que rotarla no sea un problema.
-Se generan espacios vacios al rotar, que van a ser llenados con algo. Tal vez convenga rotar antes de sacar el fondo verde y rellenar con el mismo verde para evitar que entre algo no-transparente.

**Comment by mkreyness** [comment]
donde puse (y2-y1/x2-y1) es ((y2-y1)/(x2-x1))  obviamente.

**Comment by mkreyness** [comment]
otra cosa @valentinsabbath , capaz lo mas conveniente seria generar directamente una secuencia de imagenes del tamaño del video completo, con transparencia, ubicando la cabeza en cada posicion y con la rotacion correspondiente, despues con el ffmpeg armar una pelicula con esas imagenes, y finalmente hacer el overlay de los dos videos (el original y el "fabricado") asi se procesa video una sola vez. Una especie de "animacion stop motion". Si armamos eso, yo SOLO mandaria ese videito al hosting, y lo volveria a recomponer ahi (a bajo costo).  Y si no la mas barata todavia en transmision es solo mandar la carita y reprocesar todo. Requiere mas CPU pero muuucho menos ancho de banda.

**Comment by ghost** [comment]
Genial!

**Comment by mkreyness** [comment]
Aca dice como hacer video desde imagenes:
https://trac.ffmpeg.org/wiki/Create%20a%20video%20slideshow%20from%20images

hay que ponerle que es a 24fps (si es que es asi) porque el default es 25fps.

**Comment by mkreyness** [comment]
el overlay posterior es algo que ya teniamos manejado en DelViento, seria algo asi:

ffmpeg -i base.mov -i cara.mov  -filter_complex "nullsrc=size=1280x720 [base]; [0:v] setpts=PTS-STARTPTS [cara]; [base][cara] overlay=shortest=1:x=0:y=0 [out]" -map [out] -y resultado.mp4

**Comment by LeandroBraier** [comment]
Buen día @mkreyness ! Cómo va? Me confirmás si les sirve entonces la info que les pasé?

**Comment by ghost** [comment]
Por ahora estoy reformando el script de rotacion porque achica la imagen cuando rota, pero ya le encontré la vuelta.
Ahora @mkreyness sabés como hacer para mover la imagen en una "pantalla imaginaria" según los píxeles ?

**Comment by ghost** [comment]
Ya rota perfecto

**Comment by LeandroBraier** [comment]
Buenisimo Valen! Solo nos falta posicion no? Que script estan usando? El
completo o el de los 12 segundos?

**Comment by ghost** [comment]
Si, solo falta posición. El que saqué del .txt, son 339 frames.

**Comment by ghost** [comment]
@mkreyness  , ya encontré la solución de las coordenadas en pixeles.

**Comment by mkreyness** [comment]
Lean el txt esta perfecto, como viste Valentín se está arreglando con eso. Pero no te olvides que nos falta el nivel de zoonosis, yo vi en el txt que había una coordenada Z, aunque supongo (no lo tengo a la vista) que estaba todo en 0.
Si se pudiera completar eso, nos arreglamos, siempre que tengamos una foto de cara tomada a la distancia real.

**Comment by LeandroBraier** [comment]
Genial! Necesitariamos que nos pasen como exporta en video esos primeros 12
segundos asi pasamos a la siguiente etapa de Testing si todo anda bien.

**Comment by LeandroBraier** [comment]
Yo no vo coordenada Z. En donde?

**Comment by mkreyness** [comment]
Donde dice (en el txt)
Transform   Scale
    Frame   X percent   Y percent   Z percent

**Comment by mkreyness** [comment]
esta bueno porque es un porcentaje, tomado respecto de un frame en particular, y varia.
Tambien hay un transform position donde si la coordenada Z esta en 0.

**Comment by LeandroBraier** [comment]
Ahí lo vi, claro. Porque Transform tiene coordenada Z, pero es para cuando se manejan objetos 3D. No te olvides que para After los videos son objetos 2D, por lo cual el Z siempre va a ser 0. Qué tiene que ver eso con la zoonosis de los pobres animalitos no sé, lo dirá el autocorrector  ; )

Lo que quiero decir es que los próximos pasos serían:

1) Uds nos mandan un export de cómo quedaría el video con los parámetros que pudieron tomar, así vemos si está OK.

2) Si no está OK seguimos trabajando. Si está OK avanzamos con la segunda etapa, en la cual ya la foto la haremos nosotros con una tela de chroma a la distancia real y demás como vos pedías.

**Comment by mkreyness** [comment]
Ezequiel habia dicho que se podia darle al after un par de puntos y que trackee el supuesto movimiento en el plano Z, mira que ALGO trackeó, si no diria todo 100%.
Seria importante ver que hace ese tracking cuando el pibe se acerca a la camara.

**Comment by ghost** [comment]
En algún lado tiene que estar la variable que dice cuánto se agranda y se achica la imagen. Es no creo que sea coordenada z, sino que toma la proporción de cuánto se agrandan zonas de interés como pueden ser los ojos.

Otro tema importante va a ser la "estabilización" o "centralización" de la imagen.
Esta imagen aparentemente va a funcionar bien pero porque está centrada perfectamente.
Ahora cuando se saquen fotos aleatorias, si no se evita que el participante tenga fija la cabeza en el centro y erguida, va a haber un desfasaje entre este tracking y el overlay

**Comment by mkreyness** [comment]
Si el trimming se puede hacer bien al ras, hay que definir como centro el centro del rectangulo que se obtiene y listo, acordate que no es una sino varias fotos que vamos a sacar, y al tipo se le pide que HAGA morisquetas, asi que en cada morisqueta-foto va a haber un rectangulo capaz diferente, pero si se trimmea bien, el centro es el centro.

**Comment by LeandroBraier** [comment]
@mkreyness y @valentinsabbath lo que piden lo tienen, tal cual. Eso que piden es el "Transform Scale" donde efectivamente nunca es 100% exacto (baja a 99.8361 vuelve a subir, etc). 

<img width="440" alt="captura de pantalla 2016-06-10 a las 5 13 28 p m" src="https://cloud.githubusercontent.com/assets/6719872/15976795/5b220388-2f2b-11e6-9213-8e783d7c966d.png">

En esa parte del Scale sí hay Eje Z y eso es lo que te podemos pasar. No va a haber otra cosa. Nosotros cuando tomes la foto de los usuarios nos aseguraremos de que se pongan a la misma distancia de la cámara que en la foto que tomamos de referencia para armar las coordenadas y listo, no?

**Comment by ghost** [comment]
Genial @mkreyness.
Para seguir con lo del trimming, lo que noté es que no es un trimming normal,  la imagen que pasó Lean de la cabeza está centrada porque tiene un layer transparente de la resolución del video (1280x720).
Por ahí puede ser un trimming, pero después hay que ponerla en en centro de ese layer transparente

**Comment by mkreyness** [comment]
Me gustaria ver una muestra mas completa de esa escala Z, parece ser muy suave la variacion. Vos decis que realmente el tamaño de la cabeza en la foto seria como en el plano de referencia que se tome del video ?  Lo que pasa con eso es que si en algun momento del video se ACERCA a la camara, se va a poner borroso. Para mi deberia tomarse ese plano como referencia de 100%. En todo caso si nos dicen cual es el frame a usar como 100%, escalamos nosotros todo el resto en funcion de eso.

**Comment by mkreyness** [comment]
@valentinsabbath pudiste armar una pelicula con las rotaciones/desplazamientos de la cabeza ?

**Comment by ghost** [comment]
Lamentablemente en los primeros segundos, el actor no alcanza a moverse a los costados.
Acá va una imagen con el cálculo de rotación:

![215final](https://cloud.githubusercontent.com/assets/16599421/15979382/1c33d002-2f3a-11e6-92b7-e50f21766846.jpg)

**Comment by ghost** [comment]
Eso se da porque la cabeza real tiene como eje el cuello, y la cabeza agregada rota como si estuviese al al costado en una rueda. Por ahi, si divido el resultado del cálculo por 3 exagere menos la rotación

**Comment by mkreyness** [comment]
Claro.
Me parece que la unica forma facil de solucionarlo es que la cabeza este en la parte superior de un rectangulo (o cuadrado si favorece la rotacion) del DOBLE de alto de la cabeza.

**Comment by mkreyness** [comment]
tambien podria pasar que el cuerpo del actor se ladee y en tal caso el eje de rotacion esta mucho mas abajo todavia, pero podriamos quedar con Ezequiel que el actor se mantenga derechito, no @LeandroBraier ?

**Comment by LeandroBraier** [comment]
Por el video de fondo no se preocupen. El que tiene que estar quieto es el
que de filma en la cabina no?

**Comment by mkreyness** [comment]
Ambas cosas, el actor no tiene que inclinar lateralmente el cuerpo porque el angulo que obtenemos estaria referido a un centro que no podemos determinar.

**Comment by LeandroBraier** [comment]
Pero eso es una limitacion del sistema que usan uds o de los datos que
nosotros les pasamos? Porque eso con las coordenadas de rotacion y posicion
se arregla.

No puedo limitar al video por esta limitación técnica.  Tiene que haber una
forma de calcular ese centro. Te llamo MK porque no termino de entender lo
que necesitan.

**Comment by mkreyness** [comment]
No nos viene un angulo, nos vienen coordenadas de las mejillas o de la boca. Eso determina un angulo respecto de las mejillas (o de la boca) pero no sabemos el angulo respecto de donde esta moviendose. El efecto que determino Valentin al aplicar ese ángulo es que hace que la cabeza gire como una rueda. No se me ocurre como resolverlo, tampoco soy un experto en el tema.

**Comment by mkreyness** [comment]
igual salvo que el actor este haciendo gimnasia, no veo muchos motivos para que se incline lateralmente. Yo mismo debe hacer 30 años que ni lo intento.

**Comment by mkreyness** [comment]
Con el mismo criterio, tampoco el tipo va a estar girando de perfil ni dando la espalda a la camara, no ?
Se supone que siempre esta mirando de frente.

**Comment by ghost** [comment]
Como el actor en el video de fondo seguramente se mueva para un costado me parece que podemos intentar con que el actor en el video de fondo tenga una cabeza verde y nosotros intentemos colocar la cabeza cropeada del participante sobre la cabeza verde con algun software que genere una "zona de interés" según el color

**Comment by mkreyness** [comment]
No se si hace falta lo de la cabeza verde, ya tenemos varios puntos de la cara (nariz y boca) como para poder determinar la zona de interes. Por que no probas generar vos un rectangulo con esa info y superponerlo al video, sin foto ? Si funciona, despues es cuestion de rotar la foto para que coincida sobre el rectangulo.

**Comment by mkreyness** [comment]
Hablado recien con @LeandroBraier , @valentinsabbath, el actor va a llevar algun tipo de rectangulo en la cabeza cuestion de que las coordenadas que uses para rotar sean de la BASE del rectangulo y no del medio como es ahora, y chau efecto rueda.

**Comment by ghost** [comment]
O sea que solo hay que esperar

**Comment by mkreyness** [comment]
Yo diria mientras que hagas lo que te dije de tomar la foto del tipo en un rectangulo del doble de alto y rotes ahi.
Y trata de avanzar con generar un VIDEO a partir de todas estas imagenes rotadas.

**Comment by mkreyness** [comment]
y lo otro que podes avanzar es con el scaling segun el "Transform Scale Z".

**Comment by LeandroBraier** [comment]
Claro, Valentí lo que necesito es un video para mostrarle a Eze y pedirle
que hagamos el video que dice Marce, con el actor con el rectángulo en la
cara.

Y todo lo que puedan ir avanzando en el sistema mientras tanto obvio que
también viene bien.

**Comment by ghost** [comment]
Estuve mirando el "Transform Scale Z" pero  no dice nada porque  solo hay 20 frames con eso.   @LeandroBraier necesitaría todos los frames del "Transform Scale Z"

**Comment by ghost** [comment]
Quiero hacer el video para hoy pero @mkreyness no me queda claro esto: 
Me parece que la unica forma facil de solucionarlo es que la cabeza este en la parte superior de un rectangulo (o cuadrado si favorece la rotacion) del DOBLE de alto de la cabeza.

**Comment by mkreyness** [comment]
Porque como dijiste que el angulo se aplica sobre el CENTRO de la imagen, y en realidad es una inclinacion que hay que dar sobre la base del cuello, la forma de que la base del cuello quede en el centro de la imagen es hacer la imagen del doble de alto, y con la cabeza en la mitad de arriba.
Una solucion "a lo pobre", hasta que tengamos los puntos de referencia tomados de la base inferior de un "marco" puesto alrededor de la cabeza del actor.

**Comment by ghost** [comment]
Ok! Ahora lo hago gracias!

**Comment by LeandroBraier** [comment]
@valentinsabbath te paso los datos en txt que me pasaron. Me pasaron posición, rotación y scale. Decime si te sirve.

https://mega.nz/#!Wlw1xCLS!tWR9YAXOJy7loTbdJ6Pb2_05Vy2FCHCk_2xKFMx8GLg

Video original:
https://drive.google.com/open?id=0B_6ywYX9PGKLZGliVXZEY0U4cUE

Video con prueba de trackeo incluida:
https://mega.nz/#!n9YBGL7D!90mQOCNI97g4-VF4L7dYN51RenyI3pKdMUraCoRodAg

Diganme si necesitan el trackeo de cada uno de los 4 puntos o con estos datos están OK.

**Comment by ghost** [comment]
@mkreyness hice el video (el anterior, no este) de la cabeza sola, pesa 127k! pero el problema es que el background no es transparente. No se si va a quedar utilizable.

**Comment by LeandroBraier** [comment]
COnfirmenme porfa si necesitan las coordenadas de los 4 puntos o lo que les mandé está bien. Recuerden que mañana es feriado y no puedo pedirle nada al realizador hatsa el martes.

**Comment by ghost** [comment]
@LeandroBraier a simple vista están perfectas!
Me estoy arreglando bien con esto

**Comment by mkreyness** [comment]
@valentinsabbath 127k cuantos segundos ? Si no cuanto ocuparia el conjunto de fotos transparentes ? Lo que yo quiero es transmitir a Amazon lo minimo indispensable, sin tener por supuesto que reprocesar todas las rotaciones, que ya estan hechas.

**Comment by ghost** [comment]
127k 11 segundos. En el segundo video que me pasaron las imágenes de la cabeza sueltas pesan 65MB correspondientes a 21segundos

**Comment by mkreyness** [comment]
Pero como puede haber esa diferencia de 127k a 65Mb solo por duplicar el tiempo ? Y si las comprimis a cuanto bajan esos 65 Mb ?

**Comment by LeandroBraier** [comment]
Chicos, como les queda reunión de estos temas el miércoles que viene 16 hs???

**Comment by mkreyness** [comment]
Preferiria a la mañana de ser posible.

**Comment by LeandroBraier** [comment]
Ok, a las 10 am? Vos podés Valen?

**Comment by ghost** [comment]
Puedo

**Comment by mkreyness** [comment]
10 am perfecto para mi

**Comment by LeandroBraier** [comment]
Perfecto. Quedamos entonces!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Consultita. El jueves a las 9 am pueden? 

Miércoles a la mañana Eze no puede lamentablemente.

**Comment by ghost** [comment]
Si

**Comment by mkreyness** [comment]
no, en tal caso prefiero miercoles a las 4

**Comment by LeandroBraier** [comment]
Es que Eze tampoco puede el miercoles a la tarde. Seguro no podes? Sino
cuando? Jueves a la tarde?

**Comment by mkreyness** [comment]
No, menos todavia. Siendo encima una semana corta, todo es mas complicado.
Mis dias "mas faciles" son lunes y miercoles, y no hay lunes en este caso.
Jueves a las 10 ? Y cambio lo que tengo el jueves para el miercoles.

**Comment by LeandroBraier** [comment]
Dale puede ser. Valentin vos podes? Si es asi confirmamos y pasamos la
reunión que teniamos a esa hora.

**Comment by ghost** [comment]
Jueves a las diez entonces?

**Comment by LeandroBraier** [comment]
Perfecto! Quedamos jueves a las 10 entonces! Gracias.

**Comment by LeandroBraier** [comment]
@mkreyness y @valentinsabbath cómo están?

Con Eze nos acabamos de dar cuenta de algo SUPER importante: no sabemos si el participante es HOMBRE o MUJER; por lo cual va a haber que hacer 2 videos casi igual pero uno con figura masculina y otra femenina.

Los pasos en que esto se incorpora son:
1. LOGIN: El usuario ponés sus datos, incluyendo si es hombre o mujer.
2. MÁQUINA DE PROCESAMIENTO: Selecciona para machear con la cara del usuario el video correspondiente al género seleccionado en el login. 

Nos trae mucho quilombo esto?

**Comment by mkreyness** [comment]
1. hay que agregarlo a la maquetacion.
2. @valentinsabbath al proceso que se dispara a grabar le voy a pasar ademas del numero de participante, que tenes que usar para identificar las fotos, un codigo de H o M, eso deberias usarlo para prefijar el nombre del archivo y que el proceso de la otra maquina sepa que hacer. Al video final NO le pongas esa letra, porque me complicaria la automatizacion en el server de Amazon.

**Comment by ghost** [comment]
Perfecto!!!!!

**Comment by mkreyness** [comment]
Y el tema de adulto/niño no importa ? Puede haber una diferencia importante en el tamaño de la cabeza.

**Comment by ghost** [comment]
No porque todo se recorta y se redimensiona a un tamaño inicial. Mientras
se recorte bien, lo demás esta resuelto

**Comment by LeandroBraier** [comment]
Coincido!!

**Comment by LeandroBraier** [comment]
@mkreyness recién hicimos el testing con Valen del proceso de la cabina.

Pudimos tomar la foto automática y que el sistema renderice el video. 

Nos pasó lo siguiente:

. El sistema no está programado para procesar más de 1 foto y tuvo un bug en esa prueba. Ya definimos que son 4 fotos así que Valen lo ajusta.

. Sin luz profesional el chroma recortó bastante bien. Solo convinimos que el programa recorte arbitrariamente el área del centro de la imagen para evitar cualquier manchita que pueda haber más lejos. Valen hace los ajustes también.

. La medida de la cámara de Valen a la cara la tomamos exacta, Eze tiene una cinta para la construcción. Aproximadamente son 80 cm.

Sigamos avanzando con estos pequeños cambios y cuando tenemos los videos finales (y ahi ya vamos a tener los ajustes estéticos ya hechos en las maquetaciones de Fede) cerramos el proceso de programación.

Lo que queda es el sistema de reproducción de la otra máquina y las raspis. Eso lo pongo en ticket aparte?

**Comment by mkreyness** [comment]
Por lo que leo son todas cosas de la parte de Valentin, pero probaron el tema de registro/turno/llamado/atencion ? Con el play del video mientras se graba?

Cuando decis "reproduccion de la otra maquina" a que te referis ? Lo que se ve en la zona de degustacion es siempre en las raspis, ya hablamos con @valentinsabbath como deberia hacerse, yo no puedo intervenir en nada porque no tengo ni la maquina ni las raspis. Lo que si me queda a mi pero eso tambien depende de la maquetacion es la parte del SERVER, pero eso si deberia estar en un thread aparte.
Un tema fundamental que para mi es parte de ESTE thread es el de la extraccion de los videos del dia.
@valentinsabbath acordate de que los videos finales queden en carpetas separadas por fecha y accesibles para la copia al pendrive, porque asi tienen tambien que dejarmelos en el FTP (separado por fecha). 
Entiendo que no van a estar llevandose la maquina y conectandola a internet todos los dias, por lo tanto todo lo que se pueda automatizar de la copia a pendrive, va a ayudarlos.

**Comment by LeandroBraier** [comment]
Si, lo probamos a eso también. Valentín te va a saber explicar bien.

Respecto del server qué necesitás de maquetación?

Lo abro en ticket aparte y me contás.

**Comment by mkreyness** [comment]
lo llevo al otro thread

**Comment by mkreyness** [comment]
@LeandroBraier quedo colgado lo de pasarle a Fede que me cambie la maqueta de la registracion de participantes para que incluya el dato de SEXO. Por ahora se esta forzando todo como HOMBRE, pero no lo dejemos colgado.

**Comment by LeandroBraier** [comment]
Ok MK. Le pido no te preocupes.
