### ISSUE TITLE
Maquetación Paty Chile

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Paty#5]
@FAAREIA estas son las pantallas de las que hablamos ayer que hicimos en el verano y debería adaptar a Estética Actual. 

PEDIDO ACTUALIZADO EL 23/06

1) Login

2) Listado de turnos, que en la pantalla siguiente tiene un botón grande redondo de “empezar” (se va a usar con pantalla touch o con mouse) - La pantalla esta va a ser una pantalla grande de 32 pulgadas

3) Display de turnos para la pantalla de afuera (MUY MUY simple: número y nombre del próximo turno a llamar)

En este link tenés el keyvisual:

https://mega.nz/#!PkN0XALI!4l4UWgs5lAuAX40cfeL5r2TyPAigRCuEWeNanSvsM3c

**Comment by LeandroBraier** [comment]
@mkreyness en este momento este es el otro ticket del repositorio, donde trabaja @FAAREIA las maquetas.

**Comment by mkreyness** [comment]
Ajaja, viste que habia uno y yo no estaba copiado :)
Esto que le pasaste es para el equipo local, pero tambien hay que maquetar la landing y los mails que se van a enviar, supongo que por mailchimp, no ?.  Solo lo va a acceder el propio interesado o vamos a poner un buscador, como la otra vez ? 
Y esa landing va en un hosting, que trataremos en thread aparte.
Vamos a hacer un preview en png para incluir en el mailing ? **Respuesta Leandro: Si, hacemos un preview.**

**Comment by LeandroBraier** [comment]
@mkreyness lo que no le pasé a Fede acá es porque todavía no está diseñado. 

El diseño de la landing del verano les gustó pero no les fascinó. Esta vez pidieron algo más "pro", así que vamos a hacer entregas via diseñador hasta que estén conformes y recién ahí maquetamos. Lo mismo con los mailings.

abrazo

**Comment by LeandroBraier** [comment]
Si vamos a hacer preview en PNG en el mailing igual.

**Comment by mkreyness** [comment]
Mira que no hay mucho tiempo que digamos para idas y vueltas, aunque no este definitiva la parte estetica, funcionalmente necesito saber que elementos intervienen.

**Comment by mkreyness** [comment]
donde dije "PNG" quise decir "GIF".

**Comment by mkreyness** [comment]
"Maldito corrector!" Ja ja ja

**Comment by LeandroBraier** [comment]
Si se puede GIF mejor, si.

En cuanto a los elementos de la landing dejame que lo arme bien y se los paso así lo van teniendo en cuenta. El mailing en cuanto a elementos sería igual que el del verano.

**Comment by FAAREIA** [comment]
Ahi le estuve dando al diseño. Si esta aprobado, usaría el mismo fondo para todas las pantallas de datos.

![login](https://cloud.githubusercontent.com/assets/6184969/15966761/ebb484ba-2efa-11e6-9674-edfc4e09d566.png)

**Comment by LeandroBraier** [comment]
Está bueno Fede. Dejame que lo vea con Eze y te confirmo.

Porfa ahora segui con FUCA para poder entregar alguna otra página hoy.

**Comment by mkreyness** [comment]
Pregunta @LeandroBraier se va a usar un talonario de numeros manual o podemos ponerle una numeracion correlativa automatica ?

**Comment by LeandroBraier** [comment]
Va a ser igual que en el verano segun calculo. Mañana te confirmo.

**Comment by LeandroBraier** [comment]
Confirmado con Eze. Igual que en el verano.

**Comment by mkreyness** [comment]
ok

**Comment by mkreyness** [comment]
hay alguna maqueta lista como para empezar a aplicar ?

**Comment by LeandroBraier** [comment]
Aun no. Estamos esperando que terminen de definir el keyvisual para pedirle a Fede modificaciones. Esta semana él está con FUCA a full así la que viene ya se puede meter con esto con feedback del cliente más claro.

**Comment by LeandroBraier** [comment]
@FAAREIA estamos acá en reunión con Eze. Tengo el OK para que le entregues la maquetación de estos 5 puntos con la estética que me pasaste actualmente. Una vez que tenga la parte de programación le haremos algunos ajustes mínimos pero avanzamos con eso. 

A partir de ahora frená lo de FUCA, yo le mando los adelantos que ya me pasaste. Ponete a full con eso.

**Comment by LeandroBraier** [comment]
Confirmame si para mañana a la tarde al menos podemos tener estas maquetaciones hechas.

**Comment by LeandroBraier** [comment]
Si necesitás que te llame para recordar cómo es cada pantalla avisame no hay problema.

**Comment by LeandroBraier** [comment]
@FAAREIA en la reunión achicamso la cantidad de maquetaciones de 5 a 3. Tenés solo:

1) Login

2) Listado de turnos.

3) Display de turnos externos.

Si necesitás te llamo y te aclaro cualquier duda.

abrazo

**Comment by mkreyness** [comment]
despues se agrego la que se muestra afuera con turno, nombre y apellido (grandes)

**Comment by mkreyness** [comment]
Ah, esa es la 3. Lo que pasa es que en el MAIL decia "de 5 a 2", no estaba actualizado.

**Comment by LeandroBraier** [comment]
Buen día @FAAREIA !

Te cuento que ya tenemos una devolución suficiente del Keyvisual como para adaptar estas piezas y empezar a hacer el resto.

EDITABLES Y FUENTES DEL KEYVISUAL
https://mega.nz/#F!C0ElzQiA!qA9BWiyt-VGCOroVp3QzhA

FEEDBACK SOBRE EL KEYVISUAL:
[presentacion key visual- devolucion CLIENTE.pdf](https://github.com/LeandroBraier/PatyChile/files/346387/presentacion.key.visual-.devolucion.CLIENTE.pdf)

FEEDBACK ORIGINAL SOBRE EL LOGIN:
<img width="1128" alt="captura de pantalla 2016-07-04 a las 11 02 58 a m" src="https://cloud.githubusercontent.com/assets/6719872/16562444/7ada4f4a-41d3-11e6-9a77-eaf075c3de9e.png">

**LOGIN/REGISTRAR**

En mi opinión, en el login tenés que:

1) Poner el logo de la campaña arriba bien grande, para que se entienda que es la landing de Paty (y de forma que se intercambiable en unos días cuando quede definido el logo final).

2) Teniendo los rayos, los engranajes y el gordo en el toro, el fondo podría ser blanco, siguiendo el manual de marca de la marca Paty y no específicamente el keyvisual de la campaña. Otra opción es el universo en negro del keyvisual. Lo dejo a tu criterio o si querés probar las dos.

Esta misma resolución te va a servir para el resto de las piezas web de la campaña así que es importante.

3) No olvides agregar el casillero de Hombre o Mujer, que es el único agregado de Funcionalidad que pidió @mkreyness 

4) IMPORTANTÍSIMO: Usar exactos mismos colores y fuentes que el keyvisual. Si la fuente no es web, no importa. Embebela si se puede y sino ponela como imagen y listo. NO puede usarse otras fuentes ni colores que esos.

Referencias: 

http://appnew.embluejet.com/Online/VersionOnline.aspx?eQ2gsa8jZt2hob1RIFsFy-R-2394650-R-0
http://appnew.embluejet.com/Online/VersionOnline.aspx?eQ2glccjZt2hob1RIFsFy-R-2394650-R-0

La idea sería que los diseños de las piezas de la campaña se parezcan a estas en concepto, quiero decir, en cuanto a limpieza de diseño y que genere un efecto de marca pro y moderna 100% alineada con el keyvisual de la campaña. La otra vez el cliente percibió que lo que hicimos fue una adaptación medio libre de la estética de la campaña y no lo percibió como muy pro (más que nada porque el diseño no seguía los lineamientos del key, el cliente es diseñador y se fija en el ultra detalle) 

**LISTA, TURNO Y CONFIRMADO**

Una vez definido el registrar y que te demos el OK, aplicá la misma estética a estos 3, con las mismas funcionalidades que ya tienen.

Confirmame si recibiste y llegaste con esto para hoy porfa.

abrazo

**Comment by FAAREIA** [comment]
No se si llego para hoy pero vamos a tratar.
Estuve viendo las cosas y lo malo que veo es que la tipografía elegida para titulares no tiene tildes, entonces @mkreyness si o si va a tener que reemplazar letras "raras" a caracteres comunes alfanumericos. Ni si quiera tiene la Ñ.

**Comment by LeandroBraier** [comment]
Fede, los titulares ponelos en imagen y listo. Sin texto seleccionable. No
corramos riesgos. Privilegiemos claramente la estética por sobre SEO.

2016-07-04 11:26 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Aca no importa el SEO, el tema es que un usuario se va a registrar y su nombre o apellido va a tener una tilde o una Ñ y ante eso va haber que hacer algo. Por eso es necesario reemplazar los caracteres.

**Comment by LeandroBraier** [comment]
Ah, ok. Pero para el texto del campo a completar usá otra de las
tipografías, no la de los titulares.

2016-07-04 11:32 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Si pero la pantalla que llama usuarios usa es tipografía, usar la otra quedaría mal porque tiene que ser un titular.

**Comment by LeandroBraier** [comment]
Entiendo lo que decís. OK. En ese caso vean si pueden solucionar ese tema
de los tildes. Sino podemos comprarla con tildes y Ñ si viene. Te averiguo.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Confirmado: la fuente esa es solo en inglés. Fijense si pueden resolverlo y
diganme si necesitan alguna ayuda de mi parte. En caso contrario pongamosle
que reemplace las letras con tilde por sin tilde y vemos como solucionamos
lo de la Ñ.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-07-04 11:45 GMT-03:00 Leandro Braier leandrobraier@gmail.com:

**Comment by FAAREIA** [comment]
Nunca edité una fuente. Creo que meterse en algo tan específico nos va a demandar demasiado tiempo y podemos terminar con nada. Yo reemplazaría tildes y ñ

**Comment by LeandroBraier** [comment]
Claro, pero la Ñ la reemplazamos por N?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Si

**Comment by LeandroBraier** [comment]
Mmm.. Voy a ver si podemos editar la fuente. En qué formato la necesitás?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
.otf .ttf asi después la pasó a formato web.

**Comment by LeandroBraier** [comment]
Resuelto: cambiemos la tipografía LIBERATOR para este texto en particular por otra : usemos la Chalet Comprime Milan Sixty.

**Comment by LeandroBraier** [comment]
@mkreyness confirmame si ya tenés todo lo de maquetación para tener el sistema cerrado mañana y poder hacer el testing el jueves.

Si necesitás algo más de nuestra parte avisame porfa.

abrazo

**Comment by mkreyness** [comment]
Si estamos hablando solo del stand, fui pasando lo que @FAAREIA mando, pero de esto del "chalet comprime milan sixty" no me paso nada todavia.
Y falta todo lo del sitio/landing.

**Comment by LeandroBraier** [comment]
Lo del sitio/landing está en diseño aun pero quiero que aseguremos que este
lo del stand lo antes posible.

Fede cuando puedas pasales ese cambio. Igual preparen todo con lo que
tenemos hasta ahora. Aunque sea sin ñ ni tildes.

Abrazo

**Comment by mkreyness** [comment]
Tildes no hice nada, solo eñe. Mientras Valentin no me apague la PC, puedo seguir incorporando cambios.

**Comment by mkreyness** [comment]
Ya esta funcionando con el nuevo font. Pero yo sigo viendo la "E" con acento de DEJANOS y SUMERGETE (y no era que ese texto no iba) en la pagina de registracion de usuario. Si cambio ese HTML por favor pasamelo @FAAREIA

**Comment by mkreyness** [comment]
Me refiero a que esa E se ve muy rara. Adjunto imagen.
![dejanos-y-sumergete](https://cloud.githubusercontent.com/assets/6135791/16626583/f6884aea-437f-11e6-9f55-afdff68af3be.JPG)
Puedo sacarle los acentos si quieren, total esta todo en mayuscula.

**Comment by FAAREIA** [comment]
La frasé cambió a:

`Dejanos tus datos y da<br> el primer paso hacia la Leyenda`
Fijate que tiene el tag `<br>` para el salto de línea

**Comment by mkreyness** [comment]
Listo, y no le puse el acento en "Déjanos"

**Comment by LeandroBraier** [comment]
@FAAREIA hicimos el testing. Te paso los cambios que necesitamos en estas pantallas de maquetación.

**TODAS LAS PANTALLAS**

. poner todos los textos que están en fuente Milan Sixty en negrita, para que se vea bien

. necesitamos que todo sea manejable solo con teclado, sin mouse, y de la forma más simple e intuitiva posible.

**REGISTRAR**

. cambiar lo de los botones de sexo femenino y masculino por un campo de “sexo” con un desplegable que se abra automáticamente cuando el tab llega a ese campo y solo permite los valores de "hombre" y "mujer"

. cuando el botón de Registrar esté seleccionado con el tab se cambie de color

. Que una vez registrado aparezca un pop up que se cierre dando enter y diga: ¡Ya fuiste registrado XXXNOMBREXXXXX!

**TURNO**

. Separar número y nombre. Que no se superpongan. Que se lean.

**Comment by FAAREIA** [comment]
Adjunto zip con los cambios. Todo lo que no se tocó, no lo adjunté.
Algunos detalles:
- La fuente en si es light y se ve algo bold porque el browser simula el bold pero no es el real. Si esta disponible la variable bold en .ttf o .otf joya
- Que se abra automaticamente el combo de Sexo no es posible sin un script que lo haga, y encima ya no sería un combo HTML sino una simulación según lei. Me parece mucho lio para 1 solo detalle. Fijate si con todo lo que esta ahora lo siguen necesitando.
- En turno no veo nada superpuesto pero aumenté la distancia entre usuario y número. Cualquier cosa mandame un screenshot

[Stand 16-07.zip](https://github.com/LeandroBraier/PatyChile/files/353210/Stand.16-07.zip)

**Comment by mkreyness** [comment]
el desplegable se ve medio feo en el sentido que la palabra "SEXO" antes de despegar esta toda a la izquierda cuando todo el resto del formulario esta centrado.
Ojo que no remandaste el del TURNO sino el del BOTON ROJO, no recuerdo que ahi tuviera que cambiar algo.
A mi tambien el turno me salia bien, pero tanto Lean como Valentin como lo que vimos en vivo salia con el 60% superior del numero tapando el texto, muy raro.
El unico que podria actualmente mandarte un screenshot de esto es @valentinsabbath porque lo ejecuta en el browser real (el de una raspi).
![sexo-de-costado](https://cloud.githubusercontent.com/assets/6135791/16677560/b16160c6-44ad-11e6-8434-8da2295b3260.JPG)

**Comment by mkreyness** [comment]
en el de la lista solo le agregaste los tabindex, no ? No hacen falta, justamente esa pantalla y la del botonazo rojo se manejan solo con mouse, no hay tipeo.

**Comment by LeandroBraier** [comment]
Si @mkreyness yo le pedí que hiciera TODO a prueba de teclado solo. Por las dudas.

En cuanto a la pantalla en que se encimaban nombre y número era en TURNO no en LISTA. FIjate que en el pedido te puse ese título. En TURNO necesitamos más separación entre nombre y número.

abrazo

**Comment by mkreyness** [comment]
Pero acordate que, al reves que en la entrada, dentro de la cabina va a ir solo un mouse, porque todo lo que hay que hacer es justamente clickear botones, no se tipea texto. Seria mucho mas incomodo si tienen que usar flechas y barra espaciadora de un teclado para elegir de una lista si llamar, recibir o borrar a alguien.

**Comment by LeandroBraier** [comment]
Entiendo, solo te explicaba el pedido que le hice a Fede. Obvio que con
mouse funciona. Yo le pedí además que fuera todo usable con teclado por las
dudas, nada más.

abrazo

2016-07-08 8:25 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
siempre que conecten un mouse ! Me refereria a lo feo que seria si no lo conectaran.

**Comment by mkreyness** [comment]
de hecho hay que ver si esta previsto un estantecito o algo asi en el diseño de la cabina para apoyar ese mouse con espacio suficiente para moverlo.

**Comment by FAAREIA** [comment]
Ahi corregí el bug del chrome del centrado en el combo select. Cuando se desplega con mouse se ve alineado a la izquierda, pero como tengo entendido que se va a usar teclado ahi, lo dejé asi.
Lo del turno fijense ahora, no debería de pasar. Según lo que me dicen es como que el navegador no toma el line-height seteado.

[styles.zip](https://github.com/LeandroBraier/PatyChile/files/354176/styles.zip)

**Comment by mkreyness** [comment]
Ya baje esta version de styles.css.
igual queda ALGO desplazado "sexo", porque esta centrado sin contar el triangulito, pero no creo que valga la pena dedicarle mas tiempo. Una vez que se despliega se ve bien (todo centrado).

Yo el turno siempre lo vi bien, y no tengo forma de que lo vean ustedes porque la maquina esta en una VPN entre @valentinsabbath y yo. El unico que nos lo puede confirmar es Valen desde una raspi conectada localmente.
@LeandroBraier podes incluir a @valentinsabbath ? No se si recibe las notificaciones estas, y a mi no me deja agregarlo.

**Comment by FAAREIA** [comment]
Manden foto con el celu al whatsapp cualquier cosa

**Comment by FAAREIA** [comment]
Ahi va el zip con las modificaciones de tipografía chalet, logo y el actor.
Reemplacen los archivos, no las carpetas.
En el logo de paty usé un filtro de sombra, fijense si lo ven porque necesita un navegador algo nuevo. Aca en chrome y firefox se ve bien.

[Stand 16-07.zip](https://github.com/LeandroBraier/PatyChile/files/357852/Stand.16-07.zip)

**Comment by LeandroBraier** [comment]
Gracias Fede!!! @mkreyness nos confirmás si está todo bien?

**Comment by mkreyness** [comment]
yo veo todo bien, incluyendo la sombrita de la vaca.

**Comment by LeandroBraier** [comment]
Excelente MK! Probaste lo de sexo masculino y femenino también?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
La verdad, y ya a mis 53 años, yo solo probe con sexo femenino, pero se que los que han ido por el otro camino no han vuelto, asi que tan malo no debe ser.
Ah, te referias a la pantalla. Si, probe, probe.

**Comment by LeandroBraier** [comment]
jajajajajajajaja Ojo que a veces no vuelven porque no encontraron el camino jeje Me quedo tranquilo entonces. Ya carguemos estas versiones en las máquinas. 

Uds lo testean? Me podrían mandar un videito de como funciona o algo? Hacemos un skype?

**Comment by mkreyness** [comment]
Instalate este programa y vas a estar en red con nosotros y vas a poder ver todo vos mismo.

http://download.neorouter.com/Downloads/NRFree/Update_2.3.1.4360/MacOSX/nrclient-2.3.1.4360-free-osx-x86.dmg

**Comment by mkreyness** [comment]
avisame cuando lo tengas instalado (es una pavada) y te paso datos de login por whatsapp

**Comment by mkreyness** [comment]
para ver las cosas una vez que te hayas loggeado, estos son los URLs:

10.0.0.13/usuario-registrar.html
10.0.0.13/operador.html
10.0.0.13/usuario-turno.html

podes tenerlos en 3 pestañas y ver como interactuan entre si.

**Comment by LeandroBraier** [comment]
Me instalé pero estoy en reunion, te aviso cuando puedo abrirlo. Gracias!
