### ISSUE TITLE
Hosting Paty Chile

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Paty#6]
@mkreyness dijo esto:

> Yo queria empezar a hablar del hosting porque los videos se tienen que hostear para poder mandarlos por mail, y a su vez el mailing la vez pasada lo habiamos hecho via mailchimp, entonces tengo que poner una interface para descargarlos, etc.  En definitiva del hosting SI tengo backup de todo, aunque obviamente no es tan complicado como antes lo que hay que hacer si SOLO es mandar mails.

Si el hosting es uno de Amazon podemos contratar uno con las mismas specs que en el verano? Si es así, a partir de qué fecha lo necesitás? Porque hay que pagarlo apenas lo empecemos a usar, no?

**Comment by mkreyness** [comment]
No hace falta tanta potencia como en el verano porque ahora todo se va  a procesar localmente (para mostrar el video en la parte de degustacion), pero lo que si vamos a tener mucho consumo de ancho de banda para subir necesariamente los videos ya procesados completos.
Lo unico que se procesaria en todo caso seria generar los gif para los mailings, si es que se quiere hacer eso (capaz no tiene sentido).

Se paga mientras este prendido, lo puedo prender para trabajar y apagarlo apenas termino, como hice con el que generamos temporariamente para la prueba de "preview SiguitDS".

Obviamente eso de apagar le complicaria a @FAAREIA subir las cosas, pero me las puede pasar a mi y yo las subo cuando me conecto.

**Comment by mkreyness** [comment]
Pero seria bueno ir creando alli la base de datos y el CMS de donde vas a extraer los datos para mailing, asi aprovecho el tiempo, si Valentin se las arregla sin mi para la parte del video, yo no tengo mucho para hacer hasta que esten las maquetas, y despues voy a estar contra reloj.
Si necesito tener una definicion de que se quiere hacer a nivel landing, para ver que cosas incluir en el CMS (va a haber "top divertidas", etc ?).

**Comment by LeandroBraier** [comment]
Ok, decime por favor los specs Marce y le pido a Eze el hosting mañana mismo.

Consulta: no se puede contratar primero el gratuito como están haciendo para Siguit?

**Comment by mkreyness** [comment]
1) no tenemos ningun hosting gratuito "para Siguit".
Tenemos un server gratuito que se esta por vencer, es un solo servidor por cuenta, y por unica vez.
Es un equipo minimo, no tiene memoria para tener una base de datos.
Lo de que Valentin lo use para testear el motor es ideal porque no necesita base de datos ni nada, pero no es un servidor para Siguit, es solo para pruebas de Valentin antes de pasar al verdadero servidor de Siguit que va a haber que contratar si o si.
2) tenemos un servidor que contratamos para hacer la prueba de preview infobeamer. No hace falta contratar otro, ya existe, pero esta apagado. Solo tengo que prenderlo. Cuesta 5 centavos de dolar la hora, mientras este prendido.
Calculo que con 20 horas me alcanza para lo que se puede hacer por ahora. Seria un costo de 1 dolar. 14 pesitos. Si la empresa no puede afrontarlo, lo pongo yo de mi bolsillo :)
3) Despues obviamente cuando este en uso real no se va a poder apagar, y va a costar 720 horas por mes (eso son 36 dolares) + almacenamiento (se contrata adicional cuando se necesite) + trafico (eso varia mucho segun hagamos mas proceso o menos proceso para regenerar los videos).

**Comment by LeandroBraier** [comment]
Marc: punto 2 adelante. Esta ok el presupuesto.  Avancen nomas.

**Comment by mkreyness** [comment]
ok

**Comment by mkreyness** [comment]
Respecto de lo que te decia del domain, puedo hacer que redirija al facebook de paty chile, porque dominio chileno real NO tienen.

**Comment by LeandroBraier** [comment]
Ah, excelente MK. Dale. Que redirija al Facebook de Paty Chile entonces.

https://www.facebook.com/patychile

Mejor todavía porque sino tenía que hacer aprobar la imagen especialmente.

**Comment by mkreyness** [comment]
El tema es que no funca porque Amazon ahora me da que hay que poner otros DNS diferentes de los que tuvo hace meses.
Quien maneja eso ?
Habria que ponerle estos:
ns-1851.awsdns-39.co.uk. 
ns-423.awsdns-52.com. 
ns-821.awsdns-38.net. 
ns-1192.awsdns-21.org.

**Comment by LeandroBraier** [comment]
Hay que pedirle a MS que compró el dominio desde GoDaddy entiendo. Yo le
escribo.

abrazo

2016-06-11 10:03 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
@mkreyness esto ya está funcionando todo OK no?

**Comment by mkreyness** [comment]
si, hace mucho.

**Comment by LeandroBraier** [comment]
Genial, cierro!
