### ISSUE TITLE
Server Paty Chile

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Paty#8]
@mkreyness contame qué necesitás de maquetación para el server.

**Comment by mkreyness** [comment]
La landing que van a ver cuando lleguen desde el link del mail, y si va a tener un buscador como la otra vez, top 5, etc. etc.  Hay que definir el sitio completo. Lo que hicimos antes, esta todo, pero me dijiste que no les habia gustado mucho.
Ahora el server lo tengo apagado pero si necesitas pegarle una refrescada para acordarte todo lo que habia, lo puedo encender (ojo que cobran por hora...)

**Comment by LeandroBraier** [comment]
Sería ideal si me pasás todas esas páginas así las pido, pero esto lo tengo incorporado en el ticket Landing Paty Chile, pensé que te referías a otra cosa.

Si podés pasamelo porfa.

abrazo

**Comment by mkreyness** [comment]
La landing va en el server, es todo lo mismo.
En este momento lo dejo prendido, para que las puedas ver, igual Fede debe tener copia de todo esto.
home general:
http://laleyendapaty.cl/cgi-bin/index2.pl
landing del mail:
http://laleyendapaty.cl/video.html

**Comment by LeandroBraier** [comment]
Muchas gracias MK!!!! abrazo

**Comment by mkreyness** [comment]
pero el servidor deberia apagarlo, necesitas que lo deje prendido o podes copiarte las paginas offline ?

**Comment by LeandroBraier** [comment]
Apagalo nomás. Ya me las copié.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
listo gracias.
