### ISSUE TITLE
Mailings Paty Chile JULIO

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Paty#9]
@FAAREIA apenas termines con el sistema de Paty Chile y la Landing, aplicá la misma estética a un mailing de envio de videos. La estructura es como la de antes, pero el diseño basalo en lo mismo que te pedí para las otras piezas de la campaña:

http://appnew.embluejet.com/Online/VersionOnline.aspx?eQ2gsa8jZt2hob1RIFsFy-R-2394650-R-0
http://appnew.embluejet.com/Online/VersionOnline.aspx?eQ2glccjZt2hob1RIFsFy-R-2394650-R-0

https://github.com/LeandroBraier/PatyChile/issues/7

**CONTENIDOS**

LOGO CAMPAÑA

HOLA, XXXXXXX

HAS ENTRADO EN LA LEYENDA PATY Y ESTE VIDEO LO DEMUESTRA.

((GIF ANIMADO DEL VIDEO))

HAZ CLIC PARA VERLO ONLINE Y COMPARTIRLO CON TUS AMIGOS

PATY. TRADICIÓN EN CARNES

Referencia del mailing viejo:

![captura mailing viejo paty chile](https://cloud.githubusercontent.com/assets/6719872/16563566/41f54efe-41d9-11e6-898e-52c0144b5ac8.png)

Esto puede ser para mañana a la tarde? Sino miércoles a la mañana está OK.

abrazo

**Comment by FAAREIA** [comment]
Diseño:

![paty-mailing](https://cloud.githubusercontent.com/assets/6184969/16653850/5e139f58-4429-11e6-83f1-32b1daba8f97.png)

**Comment by LeandroBraier** [comment]
@FAAREIA podrás cerrar el mailing de Paty Chile en Mailchimp ahora antes de retomar VIE TUR ?

Solo hay que cambiar el header entiendo.

**Comment by FAAREIA** [comment]
Ahi actualicé la imagen y revise el html.

**Comment by FAAREIA** [comment]
Aca van las variables, fijate si es la lista final que van a mandar estan bien seteadas:
- _|FNAME|_ -> Es un alias.
- _|MMERGE4|_ -> Url al video
- _|MMERGE3|_ -> Url del gif del video

**Comment by LeandroBraier** [comment]
Si, en Mailchimp están así.

@mkreyness confirmanos si son las mismas variables que estás usando en el CMS, pero creo que lo habíamos hablado en un momento.

**Comment by mkreyness** [comment]
las variables no estan en el CMS, lo que haces con el CMS es exportar el contenido a una maillist.
Las variables son una relacion entre como esten definidos los campos en la maillist y en el template, todo eso se maneja desde Mailchimp.
Lo importante es que el TEMPLATE tenga puestos esos codigos, que se escriben con asteriscos ademas de las barras.

**Comment by LeandroBraier** [comment]
Esta todo perfecto en mailchimp entonces.  Todo bien. Gracias!

**Comment by LeandroBraier** [comment]
@mkreyness te paso los segundos del video a tomar para el GIF.

Sería del 0.09(incluido) a 0.15(sin incluir)

Confirmame si te sirve esta data para armar el GIF y apenas empiecen las pruebas en el shopping lo probamos.

abrazo

**Comment by mkreyness** [comment]
Si, ya puse que tome del segundo 9 al 14. Los FPS que usa son 4, no se si eso esta bien o mal, tambien habria que pensarlo.

**Comment by LeandroBraier** [comment]
Mmm por eso. Habría que ver como queda por las dudas. CUando puedas pasamelo.

**Comment by mkreyness** [comment]
http://laleyendapaty.cl/gif/hombre.gif

**Comment by LeandroBraier** [comment]
Perfecto MK!
